/*
    ____                      __      ____
   /\  _`\   __             /'_ `\   /\  _`\
   \ \ \L\_\/\_\    __  _  /\ \L\ \  \ \ \L\ \ _ __    ___
    \ \  _\/\/\ \  /\ \/'\ \/_> _ <_  \ \ ,__//\`'__\ / __`\
     \ \ \/  \ \ \ \/>  </   /\ \L\ \  \ \ \/ \ \ \/ /\ \L\ \
      \ \_\   \ \_\ /\_/\_\  \ \____/   \ \_\  \ \_\ \ \____/
       \/_/    \/_/ \//\/_/   \/___/     \/_/   \/_/  \/___/

               Fix8Pro FIX Engine and Framework

Copyright (C) 2010-19 Fix8 Market Technologies Pty Ltd (ABN 29 167 027 198)
All Rights Reserved. [http://www.fix8mt.com] <heretohelp@fix8mt.com>

THIS FILE IS PROPRIETARY AND  CONFIDENTIAL. NO PART OF THIS FILE MAY BE REPRODUCED,  STORED
IN A RETRIEVAL SYSTEM,  OR TRANSMITTED, IN ANY FORM OR ANY MEANS,  ELECTRONIC, PHOTOSTATIC,
RECORDED OR OTHERWISE, WITHOUT THE PRIOR AND  EXPRESS WRITTEN  PERMISSION  OF  FIX8  MARKET
TECHNOLOGIES PTY LTD.
*/

// Autogenerated on 2019-09-03 12:19:32.935044
// /home/sergey/src/f8/fix8pro/compiler/py/f8c/f8c.py --template ufe_java_fields ufe_cpp_fields ufe_cs_fields ufe_py_fields --output-dir ./generated --schema-dir /home/sergey/src/f8/fix8pro/schema/xml FIX50SP2 FIX42 FIX44 FIX40 FIX41 FIX43 FIX50 FIX50SP1
// DO NOT EDIT!

package com.fix8mt.ufe.FIX40;

public final class ufe_java_fields_fix40 {

    // Account(1): CHAR
    public static final class Account {
        public static final int tag = 1;
    }

    // AdvId(2): INT
    public static final class AdvId {
        public static final int tag = 2;
    }

    // AdvRefID(3): INT
    public static final class AdvRefID {
        public static final int tag = 3;
    }

    // AdvSide(4): CHAR
    public static final class AdvSide {
        public static final int tag = 4;
        public static final char BUY = 'B';
        public static final char SELL = 'S';
        public static final char TRADE = 'T';
        public static final char CROSS = 'X';
    }

    // AdvTransType(5): CHAR
    public static final class AdvTransType {
        public static final int tag = 5;
        public static final char CANCEL = 'C';
        public static final char NEW = 'N';
        public static final char REPLACE = 'R';
    }

    // AvgPx(6): FLOAT
    public static final class AvgPx {
        public static final int tag = 6;
    }

    // BeginSeqNo(7): INT
    public static final class BeginSeqNo {
        public static final int tag = 7;
    }

    // BeginString(8): CHAR
    public static final class BeginString {
        public static final int tag = 8;
    }

    // BodyLength(9): INT
    public static final class BodyLength {
        public static final int tag = 9;
    }

    // CheckSum(10): CHAR
    public static final class CheckSum {
        public static final int tag = 10;
    }

    // ClOrdID(11): CHAR
    public static final class ClOrdID {
        public static final int tag = 11;
    }

    // Commission(12): FLOAT
    public static final class Commission {
        public static final int tag = 12;
    }

    // CommType(13): CHAR
    public static final class CommType {
        public static final int tag = 13;
        public static final char PER_SHARE = '1';
        public static final char PERCENTAGE = '2';
        public static final char ABSOLUTE = '3';
    }

    // CumQty(14): INT
    public static final class CumQty {
        public static final int tag = 14;
    }

    // Currency(15): CHAR
    public static final class Currency {
        public static final int tag = 15;
    }

    // EndSeqNo(16): INT
    public static final class EndSeqNo {
        public static final int tag = 16;
    }

    // ExecID(17): INT
    public static final class ExecID {
        public static final int tag = 17;
    }

    // ExecInst(18): CHAR
    public static final class ExecInst {
        public static final int tag = 18;
        public static final char STAY_ON_OFFERSIDE = '0';
        public static final char NOT_HELD = '1';
        public static final char WORK = '2';
        public static final char GO_ALONG = '3';
        public static final char OVER_THE_DAY = '4';
        public static final char HELD = '5';
        public static final char PARTICIPATE_DONT_INITIATE = '6';
        public static final char STRICT_SCALE = '7';
        public static final char TRY_TO_SCALE = '8';
        public static final char STAY_ON_BIDSIDE = '9';
        public static final char NO_CROSS = 'A';
        public static final char OK_TO_CROSS = 'B';
        public static final char CALL_FIRST = 'C';
        public static final char PERCENT_OF_VOLUME = 'D';
        public static final char DO_NOT_INCREASE = 'E';
        public static final char DO_NOT_REDUCE = 'F';
        public static final char ALL_OR_NONE = 'G';
        public static final char INSTITUTIONS_ONLY = 'I';
        public static final char LAST_PEG = 'L';
        public static final char MID_PRICE_PEG = 'M';
        public static final char NON_NEGOTIABLE = 'N';
        public static final char OPENING_PEG = 'O';
        public static final char MARKET_PEG = 'P';
        public static final char PRIMARY_PEG = 'R';
        public static final char SUSPEND = 'S';
    }

    // ExecRefID(19): INT
    public static final class ExecRefID {
        public static final int tag = 19;
    }

    // ExecTransType(20): CHAR
    public static final class ExecTransType {
        public static final int tag = 20;
        public static final char NEW = '0';
        public static final char CANCEL = '1';
        public static final char CORRECT = '2';
        public static final char STATUS = '3';
    }

    // HandlInst(21): CHAR
    public static final class HandlInst {
        public static final int tag = 21;
        public static final char AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION = '1';
        public static final char AUTOMATED_EXECUTION_ORDER_PUBLIC_BROKER_INTERVENTION_OK = '2';
        public static final char MANUAL_ORDER_BEST_EXECUTION = '3';
    }

    // IDSource(22): CHAR
    public static final class IDSource {
        public static final int tag = 22;
        public static final char CUSIP = '1';
        public static final char SEDOL = '2';
        public static final char QUIK = '3';
        public static final char ISIN_NUMBER = '4';
        public static final char RIC_CODE = '5';
    }

    // IOIid(23): INT
    public static final class IOIid {
        public static final int tag = 23;
    }

    // IOIOthSvc(24): CHAR
    public static final class IOIOthSvc {
        public static final int tag = 24;
        public static final char AUTEX = 'A';
        public static final char BRIDGE = 'B';
    }

    // IOIQltyInd(25): CHAR
    public static final class IOIQltyInd {
        public static final int tag = 25;
        public static final char HIGH = 'H';
        public static final char LOW = 'L';
        public static final char MEDIUM = 'M';
    }

    // IOIRefID(26): INT
    public static final class IOIRefID {
        public static final int tag = 26;
    }

    // IOIShares(27): CHAR
    public static final class IOIShares {
        public static final int tag = 27;
        public static final char LARGE = 'L';
        public static final char MEDIUM = 'M';
        public static final char SMALL = 'S';
    }

    // IOITransType(28): CHAR
    public static final class IOITransType {
        public static final int tag = 28;
        public static final char CANCEL = 'C';
        public static final char NEW = 'N';
        public static final char REPLACE = 'R';
    }

    // LastCapacity(29): CHAR
    public static final class LastCapacity {
        public static final int tag = 29;
        public static final char AGENT = '1';
        public static final char CROSS_AS_AGENT = '2';
        public static final char CROSS_AS_PRINCIPAL = '3';
        public static final char PRINCIPAL = '4';
    }

    // LastMkt(30): CHAR
    public static final class LastMkt {
        public static final int tag = 30;
    }

    // LastPx(31): FLOAT
    public static final class LastPx {
        public static final int tag = 31;
    }

    // LastShares(32): INT
    public static final class LastShares {
        public static final int tag = 32;
    }

    // LinesOfText(33): INT
    public static final class LinesOfText {
        public static final int tag = 33;
    }

    // MsgSeqNum(34): INT
    public static final class MsgSeqNum {
        public static final int tag = 34;
    }

    // MsgType(35): STRING
    public static final class MsgType {
        public static final int tag = 35;
        public static final String HEARTBEAT = "0";
        public static final String TEST_REQUEST = "1";
        public static final String RESEND_REQUEST = "2";
        public static final String REJECT = "3";
        public static final String SEQUENCE_RESET = "4";
        public static final String LOGOUT = "5";
        public static final String INDICATION_OF_INTEREST = "6";
        public static final String ADVERTISEMENT = "7";
        public static final String EXECUTION_REPORT = "8";
        public static final String ORDER_CANCEL_REJECT = "9";
        public static final String LOGON = "A";
        public static final String NEWS = "B";
        public static final String EMAIL = "C";
        public static final String ORDER_D = "D";
        public static final String ORDER_E = "E";
        public static final String ORDER_CANCEL_REQUEST = "F";
        public static final String ORDER_CANCEL_REPLACE_REQUEST = "G";
        public static final String ORDER_STATUS_REQUEST = "H";
        public static final String ALLOCATION = "J";
        public static final String LIST_CANCEL_REQUEST = "K";
        public static final String LIST_EXECUTE = "L";
        public static final String LIST_STATUS_REQUEST = "M";
        public static final String LIST_STATUS = "N";
        public static final String ALLOCATION_ACK = "P";
        public static final String DONT_KNOW_TRADE = "Q";
        public static final String QUOTE_REQUEST = "R";
        public static final String QUOTE = "S";
    }

    // NewSeqNo(36): INT
    public static final class NewSeqNo {
        public static final int tag = 36;
    }

    // OrderID(37): CHAR
    public static final class OrderID {
        public static final int tag = 37;
    }

    // OrderQty(38): INT
    public static final class OrderQty {
        public static final int tag = 38;
    }

    // OrdStatus(39): CHAR
    public static final class OrdStatus {
        public static final int tag = 39;
        public static final char NEW = '0';
        public static final char PARTIALLY_FILLED = '1';
        public static final char FILLED = '2';
        public static final char DONE_FOR_DAY = '3';
        public static final char CANCELED = '4';
        public static final char REPLACED = '5';
        public static final char PENDING_CANCEL_REPLACE = '6';
        public static final char STOPPED = '7';
        public static final char REJECTED = '8';
        public static final char SUSPENDED = '9';
        public static final char PENDING_NEW = 'A';
        public static final char CALCULATED = 'B';
        public static final char EXPIRED = 'C';
    }

    // OrdType(40): CHAR
    public static final class OrdType {
        public static final int tag = 40;
        public static final char MARKET = '1';
        public static final char LIMIT = '2';
        public static final char STOP = '3';
        public static final char STOP_LIMIT = '4';
        public static final char MARKET_ON_CLOSE = '5';
        public static final char WITH_OR_WITHOUT = '6';
        public static final char LIMIT_OR_BETTER = '7';
        public static final char LIMIT_WITH_OR_WITHOUT = '8';
        public static final char ON_BASIS = '9';
        public static final char ON_CLOSE = 'A';
        public static final char LIMIT_ON_CLOSE = 'B';
        public static final char FOREX = 'C';
        public static final char PREVIOUSLY_QUOTED = 'D';
        public static final char PREVIOUSLY_INDICATED = 'E';
        public static final char PEGGED = 'P';
    }

    // OrigClOrdID(41): CHAR
    public static final class OrigClOrdID {
        public static final int tag = 41;
    }

    // OrigTime(42): UTCTIMESTAMP
    public static final class OrigTime {
        public static final int tag = 42;
    }

    // PossDupFlag(43): CHAR
    public static final class PossDupFlag {
        public static final int tag = 43;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // Price(44): FLOAT
    public static final class Price {
        public static final int tag = 44;
    }

    // RefSeqNum(45): INT
    public static final class RefSeqNum {
        public static final int tag = 45;
    }

    // RelatdSym(46): CHAR
    public static final class RelatdSym {
        public static final int tag = 46;
    }

    // Rule80A(47): CHAR
    public static final class Rule80A {
        public static final int tag = 47;
        public static final char AGENCY_SINGLE_ORDER = 'A';
        public static final char PROGRAM_ORDER_NON_INDEX_ARB_FOR_MEMBER_FIRM_ORG = 'C';
        public static final char PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG = 'D';
        public static final char INDIVIDUAL_INVESTOR_SINGLE_ORDER = 'I';
        public static final char PROGRAM_ORDER_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER = 'J';
        public static final char PROGRAM_ORDER_NON_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER = 'K';
        public static final char PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER = 'M';
        public static final char PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_MEMBER = 'N';
        public static final char PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_AGENCY = 'U';
        public static final char ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER = 'W';
        public static final char PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_AGENCY = 'Y';
    }

    // SecurityID(48): CHAR
    public static final class SecurityID {
        public static final int tag = 48;
    }

    // SenderCompID(49): CHAR
    public static final class SenderCompID {
        public static final int tag = 49;
    }

    // SenderSubID(50): CHAR
    public static final class SenderSubID {
        public static final int tag = 50;
    }

    // SendingDate(51): LOCALMKTDATE
    public static final class SendingDate {
        public static final int tag = 51;
    }

    // SendingTime(52): UTCTIMESTAMP
    public static final class SendingTime {
        public static final int tag = 52;
    }

    // Shares(53): INT
    public static final class Shares {
        public static final int tag = 53;
    }

    // Side(54): CHAR
    public static final class Side {
        public static final int tag = 54;
        public static final char BUY = '1';
        public static final char SELL = '2';
        public static final char BUY_MINUS = '3';
        public static final char SELL_PLUS = '4';
        public static final char SELL_SHORT = '5';
        public static final char SELL_SHORT_EXEMPT = '6';
    }

    // Symbol(55): CHAR
    public static final class Symbol {
        public static final int tag = 55;
    }

    // TargetCompID(56): CHAR
    public static final class TargetCompID {
        public static final int tag = 56;
    }

    // TargetSubID(57): CHAR
    public static final class TargetSubID {
        public static final int tag = 57;
    }

    // Text(58): CHAR
    public static final class Text {
        public static final int tag = 58;
    }

    // TimeInForce(59): CHAR
    public static final class TimeInForce {
        public static final int tag = 59;
        public static final char DAY = '0';
        public static final char GOOD_TILL_CANCEL = '1';
        public static final char AT_THE_OPENING = '2';
        public static final char IMMEDIATE_OR_CANCEL = '3';
        public static final char FILL_OR_KILL = '4';
        public static final char GOOD_TILL_CROSSING = '5';
        public static final char GOOD_TILL_DATE = '6';
    }

    // TransactTime(60): UTCTIMESTAMP
    public static final class TransactTime {
        public static final int tag = 60;
    }

    // Urgency(61): CHAR
    public static final class Urgency {
        public static final int tag = 61;
        public static final char NORMAL = '0';
        public static final char FLASH = '1';
        public static final char BACKGROUND = '2';
    }

    // ValidUntilTime(62): UTCTIMESTAMP
    public static final class ValidUntilTime {
        public static final int tag = 62;
    }

    // SettlmntTyp(63): CHAR
    public static final class SettlmntTyp {
        public static final int tag = 63;
        public static final char REGULAR = '0';
        public static final char CASH = '1';
        public static final char NEXT_DAY = '2';
        public static final char T_PLUS_2 = '3';
        public static final char T_PLUS_3 = '4';
        public static final char T_PLUS_4 = '5';
        public static final char FUTURE = '6';
        public static final char WHEN_ISSUED = '7';
        public static final char SELLERS_OPTION = '8';
        public static final char T_PLUS_5 = '9';
    }

    // FutSettDate(64): LOCALMKTDATE
    public static final class FutSettDate {
        public static final int tag = 64;
    }

    // SymbolSfx(65): CHAR
    public static final class SymbolSfx {
        public static final int tag = 65;
    }

    // ListID(66): CHAR
    public static final class ListID {
        public static final int tag = 66;
    }

    // ListSeqNo(67): INT
    public static final class ListSeqNo {
        public static final int tag = 67;
    }

    // ListNoOrds(68): INT
    public static final class ListNoOrds {
        public static final int tag = 68;
    }

    // ListExecInst(69): CHAR
    public static final class ListExecInst {
        public static final int tag = 69;
    }

    // AllocID(70): INT
    public static final class AllocID {
        public static final int tag = 70;
    }

    // AllocTransType(71): CHAR
    public static final class AllocTransType {
        public static final int tag = 71;
        public static final char NEW = '0';
        public static final char REPLACE = '1';
        public static final char CANCEL = '2';
    }

    // RefAllocID(72): INT
    public static final class RefAllocID {
        public static final int tag = 72;
    }

    // NoOrders(73): INT
    public static final class NoOrders {
        public static final int tag = 73;
    }

    // AvgPrxPrecision(74): INT
    public static final class AvgPrxPrecision {
        public static final int tag = 74;
    }

    // TradeDate(75): LOCALMKTDATE
    public static final class TradeDate {
        public static final int tag = 75;
    }

    // ExecBroker(76): CHAR
    public static final class ExecBroker {
        public static final int tag = 76;
    }

    // OpenClose(77): CHAR
    public static final class OpenClose {
        public static final int tag = 77;
    }

    // NoAllocs(78): INT
    public static final class NoAllocs {
        public static final int tag = 78;
    }

    // AllocAccount(79): CHAR
    public static final class AllocAccount {
        public static final int tag = 79;
    }

    // AllocShares(80): INT
    public static final class AllocShares {
        public static final int tag = 80;
    }

    // ProcessCode(81): CHAR
    public static final class ProcessCode {
        public static final int tag = 81;
        public static final char REGULAR = '0';
        public static final char SOFT_DOLLAR = '1';
        public static final char STEP_IN = '2';
        public static final char STEP_OUT = '3';
        public static final char SOFT_DOLLAR_STEP_IN = '4';
        public static final char SOFT_DOLLAR_STEP_OUT = '5';
        public static final char PLAN_SPONSOR = '6';
    }

    // NoRpts(82): INT
    public static final class NoRpts {
        public static final int tag = 82;
    }

    // RptSeq(83): INT
    public static final class RptSeq {
        public static final int tag = 83;
    }

    // CxlQty(84): INT
    public static final class CxlQty {
        public static final int tag = 84;
    }

    // NoDlvyInst(85): INT
    public static final class NoDlvyInst {
        public static final int tag = 85;
    }

    // DlvyInst(86): CHAR
    public static final class DlvyInst {
        public static final int tag = 86;
    }

    // AllocStatus(87): INT
    public static final class AllocStatus {
        public static final int tag = 87;
        public static final int ACCEPTED = 0;
        public static final int REJECTED = 1;
        public static final int PARTIAL_ACCEPT = 2;
        public static final int RECEIVED = 3;
    }

    // AllocRejCode(88): INT
    public static final class AllocRejCode {
        public static final int tag = 88;
        public static final int UNKNOWN_ACCOUNT = 0;
        public static final int INCORRECT_QUANTITY = 1;
        public static final int INCORRECT_AVERAGE_PRICE = 2;
        public static final int UNKNOWN_EXECUTING_BROKER_MNEMONIC = 3;
        public static final int COMMISSION_DIFFERENCE = 4;
        public static final int UNKNOWN_ORDERID = 5;
        public static final int UNKNOWN_LISTID = 6;
        public static final int OTHER = 7;
    }

    // Signature(89): DATA
    public static final class Signature {
        public static final int tag = 89;
    }

    // SecureDataLen(90): LENGTH
    public static final class SecureDataLen {
        public static final int tag = 90;
    }

    // SecureData(91): DATA
    public static final class SecureData {
        public static final int tag = 91;
    }

    // BrokerOfCredit(92): CHAR
    public static final class BrokerOfCredit {
        public static final int tag = 92;
    }

    // SignatureLength(93): LENGTH
    public static final class SignatureLength {
        public static final int tag = 93;
    }

    // EmailType(94): CHAR
    public static final class EmailType {
        public static final int tag = 94;
        public static final char NEW = '0';
        public static final char REPLY = '1';
        public static final char ADMIN_REPLY = '2';
    }

    // RawDataLength(95): LENGTH
    public static final class RawDataLength {
        public static final int tag = 95;
    }

    // RawData(96): DATA
    public static final class RawData {
        public static final int tag = 96;
    }

    // PossResend(97): CHAR
    public static final class PossResend {
        public static final int tag = 97;
    }

    // EncryptMethod(98): INT
    public static final class EncryptMethod {
        public static final int tag = 98;
        public static final int NONE = 0;
        public static final int PKCS = 1;
        public static final int DES = 2;
        public static final int PKCS_DES = 3;
        public static final int PGP_DES = 4;
        public static final int PGP_DES_MD5 = 5;
        public static final int PEM_DES_MD5 = 6;
    }

    // StopPx(99): FLOAT
    public static final class StopPx {
        public static final int tag = 99;
    }

    // ExDestination(100): CHAR
    public static final class ExDestination {
        public static final int tag = 100;
        public static final char NONE = '0';
        public static final char POSIT = '4';
    }

    // CxlRejReason(102): INT
    public static final class CxlRejReason {
        public static final int tag = 102;
        public static final int TOO_LATE_TO_CANCEL = 0;
        public static final int UNKNOWN_ORDER = 1;
    }

    // OrdRejReason(103): INT
    public static final class OrdRejReason {
        public static final int tag = 103;
        public static final int BROKER_OPTION = 0;
        public static final int UNKNOWN_SYMBOL = 1;
        public static final int EXCHANGE_CLOSED = 2;
        public static final int ORDER_EXCEEDS_LIMIT = 3;
        public static final int TOO_LATE_TO_ENTER = 4;
    }

    // IOIQualifier(104): CHAR
    public static final class IOIQualifier {
        public static final int tag = 104;
        public static final char ALL_OR_NONE = 'A';
        public static final char AT_THE_CLOSE = 'C';
        public static final char IN_TOUCH_WITH = 'I';
        public static final char LIMIT = 'L';
        public static final char MORE_BEHIND = 'M';
        public static final char AT_THE_OPEN = 'O';
        public static final char TAKING_A_POSITION = 'P';
        public static final char CURRENT_QUOTE = 'Q';
        public static final char PORTFOLIO_SHOW_N = 'S';
        public static final char THROUGH_THE_DAY = 'T';
        public static final char VERSUS = 'V';
        public static final char INDICATION = 'W';
        public static final char CROSSING_OPPORTUNITY = 'X';
    }

    // WaveNo(105): CHAR
    public static final class WaveNo {
        public static final int tag = 105;
    }

    // Issuer(106): CHAR
    public static final class Issuer {
        public static final int tag = 106;
    }

    // SecurityDesc(107): CHAR
    public static final class SecurityDesc {
        public static final int tag = 107;
    }

    // HeartBtInt(108): INT
    public static final class HeartBtInt {
        public static final int tag = 108;
    }

    // ClientID(109): CHAR
    public static final class ClientID {
        public static final int tag = 109;
    }

    // MinQty(110): INT
    public static final class MinQty {
        public static final int tag = 110;
    }

    // MaxFloor(111): INT
    public static final class MaxFloor {
        public static final int tag = 111;
    }

    // TestReqID(112): CHAR
    public static final class TestReqID {
        public static final int tag = 112;
    }

    // ReportToExch(113): CHAR
    public static final class ReportToExch {
        public static final int tag = 113;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // LocateReqd(114): CHAR
    public static final class LocateReqd {
        public static final int tag = 114;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // OnBehalfOfCompID(115): CHAR
    public static final class OnBehalfOfCompID {
        public static final int tag = 115;
    }

    // OnBehalfOfSubID(116): CHAR
    public static final class OnBehalfOfSubID {
        public static final int tag = 116;
    }

    // QuoteID(117): CHAR
    public static final class QuoteID {
        public static final int tag = 117;
    }

    // NetMoney(118): FLOAT
    public static final class NetMoney {
        public static final int tag = 118;
    }

    // SettlCurrAmt(119): FLOAT
    public static final class SettlCurrAmt {
        public static final int tag = 119;
    }

    // SettlCurrency(120): CHAR
    public static final class SettlCurrency {
        public static final int tag = 120;
    }

    // ForexReq(121): CHAR
    public static final class ForexReq {
        public static final int tag = 121;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // OrigSendingTime(122): UTCTIMESTAMP
    public static final class OrigSendingTime {
        public static final int tag = 122;
    }

    // GapFillFlag(123): CHAR
    public static final class GapFillFlag {
        public static final int tag = 123;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // NoExecs(124): INT
    public static final class NoExecs {
        public static final int tag = 124;
    }

    // CxlType(125): CHAR
    public static final class CxlType {
        public static final int tag = 125;
        public static final char FULL_REMAINING_QUANTITY = 'F';
        public static final char PARTIAL_CANCEL = 'P';
    }

    // ExpireTime(126): UTCTIMESTAMP
    public static final class ExpireTime {
        public static final int tag = 126;
    }

    // DKReason(127): CHAR
    public static final class DKReason {
        public static final int tag = 127;
        public static final char UNKNOWN_SYMBOL = 'A';
        public static final char WRONG_SIDE = 'B';
        public static final char QUANTITY_EXCEEDS_ORDER = 'C';
        public static final char NO_MATCHING_ORDER = 'D';
        public static final char PRICE_EXCEEDS_LIMIT = 'E';
        public static final char OTHER = 'Z';
    }

    // DeliverToCompID(128): CHAR
    public static final class DeliverToCompID {
        public static final int tag = 128;
    }

    // DeliverToSubID(129): CHAR
    public static final class DeliverToSubID {
        public static final int tag = 129;
    }

    // IOINaturalFlag(130): CHAR
    public static final class IOINaturalFlag {
        public static final int tag = 130;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // QuoteReqID(131): CHAR
    public static final class QuoteReqID {
        public static final int tag = 131;
    }

    // BidPx(132): FLOAT
    public static final class BidPx {
        public static final int tag = 132;
    }

    // OfferPx(133): FLOAT
    public static final class OfferPx {
        public static final int tag = 133;
    }

    // BidSize(134): INT
    public static final class BidSize {
        public static final int tag = 134;
    }

    // OfferSize(135): INT
    public static final class OfferSize {
        public static final int tag = 135;
    }

    // NoMiscFees(136): INT
    public static final class NoMiscFees {
        public static final int tag = 136;
    }

    // MiscFeeAmt(137): FLOAT
    public static final class MiscFeeAmt {
        public static final int tag = 137;
    }

    // MiscFeeCurr(138): CHAR
    public static final class MiscFeeCurr {
        public static final int tag = 138;
    }

    // MiscFeeType(139): CHAR
    public static final class MiscFeeType {
        public static final int tag = 139;
        public static final char REGULATORY = '1';
        public static final char TAX = '2';
        public static final char LOCAL_COMMISSION = '3';
        public static final char EXCHANGE_FEES = '4';
        public static final char STAMP = '5';
        public static final char LEVY = '6';
        public static final char OTHER = '7';
    }

    // PrevClosePx(140): FLOAT
    public static final class PrevClosePx {
        public static final int tag = 140;
    }
}
