/*
    ____                      __      ____
   /\  _`\   __             /'_ `\   /\  _`\
   \ \ \L\_\/\_\    __  _  /\ \L\ \  \ \ \L\ \ _ __    ___
    \ \  _\/\/\ \  /\ \/'\ \/_> _ <_  \ \ ,__//\`'__\ / __`\
     \ \ \/  \ \ \ \/>  </   /\ \L\ \  \ \ \/ \ \ \/ /\ \L\ \
      \ \_\   \ \_\ /\_/\_\  \ \____/   \ \_\  \ \_\ \ \____/
       \/_/    \/_/ \//\/_/   \/___/     \/_/   \/_/  \/___/

               Fix8Pro FIX Engine and Framework

Copyright (C) 2010-19 Fix8 Market Technologies Pty Ltd (ABN 29 167 027 198)
All Rights Reserved. [http://www.fix8mt.com] <heretohelp@fix8mt.com>

THIS FILE IS PROPRIETARY AND  CONFIDENTIAL. NO PART OF THIS FILE MAY BE REPRODUCED,  STORED
IN A RETRIEVAL SYSTEM,  OR TRANSMITTED, IN ANY FORM OR ANY MEANS,  ELECTRONIC, PHOTOSTATIC,
RECORDED OR OTHERWISE, WITHOUT THE PRIOR AND  EXPRESS WRITTEN  PERMISSION  OF  FIX8  MARKET
TECHNOLOGIES PTY LTD.
*/

// Autogenerated on 2019-09-03 12:19:32.409746
// /home/sergey/src/f8/fix8pro/compiler/py/f8c/f8c.py --template ufe_java_fields ufe_cpp_fields ufe_cs_fields ufe_py_fields --output-dir ./generated --schema-dir /home/sergey/src/f8/fix8pro/schema/xml FIX50SP2 FIX42 FIX44 FIX40 FIX41 FIX43 FIX50 FIX50SP1
// DO NOT EDIT!

package com.fix8mt.ufe.FIX42;

public final class ufe_java_fields_fix42 {

    // Account(1): STRING
    public static final class Account {
        public static final int tag = 1;
    }

    // AdvId(2): STRING
    public static final class AdvId {
        public static final int tag = 2;
    }

    // AdvRefID(3): STRING
    public static final class AdvRefID {
        public static final int tag = 3;
    }

    // AdvSide(4): CHAR
    public static final class AdvSide {
        public static final int tag = 4;
        public static final char BUY = 'B';
        public static final char SELL = 'S';
        public static final char TRADE = 'T';
        public static final char CROSS = 'X';
    }

    // AdvTransType(5): STRING
    public static final class AdvTransType {
        public static final int tag = 5;
        public static final String CANCEL = "C";
        public static final String NEW = "N";
        public static final String REPLACE = "R";
    }

    // AvgPx(6): PRICE
    public static final class AvgPx {
        public static final int tag = 6;
    }

    // BeginSeqNo(7): INT
    public static final class BeginSeqNo {
        public static final int tag = 7;
    }

    // BeginString(8): STRING
    public static final class BeginString {
        public static final int tag = 8;
    }

    // BodyLength(9): INT
    public static final class BodyLength {
        public static final int tag = 9;
    }

    // CheckSum(10): STRING
    public static final class CheckSum {
        public static final int tag = 10;
    }

    // ClOrdID(11): STRING
    public static final class ClOrdID {
        public static final int tag = 11;
    }

    // Commission(12): AMT
    public static final class Commission {
        public static final int tag = 12;
    }

    // CommType(13): CHAR
    public static final class CommType {
        public static final int tag = 13;
        public static final char PER_SHARE = '1';
        public static final char PERCENTAGE = '2';
        public static final char ABSOLUTE = '3';
    }

    // CumQty(14): QTY
    public static final class CumQty {
        public static final int tag = 14;
    }

    // Currency(15): CURRENCY
    public static final class Currency {
        public static final int tag = 15;
    }

    // EndSeqNo(16): INT
    public static final class EndSeqNo {
        public static final int tag = 16;
    }

    // ExecID(17): STRING
    public static final class ExecID {
        public static final int tag = 17;
    }

    // ExecInst(18): MULTIPLEVALUESTRING
    public static final class ExecInst {
        public static final int tag = 18;
        public static final String STAY_ON_OFFERSIDE = "0";
        public static final String NOT_HELD = "1";
        public static final String WORK = "2";
        public static final String GO_ALONG = "3";
        public static final String OVER_THE_DAY = "4";
        public static final String HELD = "5";
        public static final String PARTICIPATE_DONT_INITIATE = "6";
        public static final String STRICT_SCALE = "7";
        public static final String TRY_TO_SCALE = "8";
        public static final String STAY_ON_BIDSIDE = "9";
        public static final String NO_CROSS = "A";
        public static final String OK_TO_CROSS = "B";
        public static final String CALL_FIRST = "C";
        public static final String PERCENT_OF_VOLUME = "D";
        public static final String DO_NOT_INCREASE = "E";
        public static final String DO_NOT_REDUCE = "F";
        public static final String ALL_OR_NONE = "G";
        public static final String INSTITUTIONS_ONLY = "I";
        public static final String LAST_PEG = "L";
        public static final String MID_PRICE_PEG = "M";
        public static final String NON_NEGOTIABLE = "N";
        public static final String OPENING_PEG = "O";
        public static final String MARKET_PEG = "P";
        public static final String PRIMARY_PEG = "R";
        public static final String SUSPEND = "S";
        public static final String FIXED_PEG_TO_LOCAL_BEST_BID_OR_OFFER_AT_TIME_OF_ORDER = "T";
        public static final String CUSTOMER_DISPLAY_INSTRUCTION = "U";
        public static final String NETTING = "V";
        public static final String PEG_TO_VWAP = "W";
    }

    // ExecRefID(19): STRING
    public static final class ExecRefID {
        public static final int tag = 19;
    }

    // ExecTransType(20): CHAR
    public static final class ExecTransType {
        public static final int tag = 20;
        public static final char NEW = '0';
        public static final char CANCEL = '1';
        public static final char CORRECT = '2';
        public static final char STATUS = '3';
    }

    // HandlInst(21): CHAR
    public static final class HandlInst {
        public static final int tag = 21;
        public static final char AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION = '1';
        public static final char AUTOMATED_EXECUTION_ORDER_PUBLIC_BROKER_INTERVENTION_OK = '2';
        public static final char MANUAL_ORDER_BEST_EXECUTION = '3';
    }

    // IDSource(22): STRING
    public static final class IDSource {
        public static final int tag = 22;
        public static final String CUSIP = "1";
        public static final String SEDOL = "2";
        public static final String QUIK = "3";
        public static final String ISIN_NUMBER = "4";
        public static final String RIC_CODE = "5";
        public static final String ISO_CURRENCY_CODE = "6";
        public static final String ISO_COUNTRY_CODE = "7";
        public static final String EXCHANGE_SYMBOL = "8";
        public static final String CONSOLIDATED_TAPE_ASSOCIATION = "9";
    }

    // IOIid(23): STRING
    public static final class IOIid {
        public static final int tag = 23;
    }

    // IOIOthSvc(24): CHAR
    public static final class IOIOthSvc {
        public static final int tag = 24;
    }

    // IOIQltyInd(25): CHAR
    public static final class IOIQltyInd {
        public static final int tag = 25;
        public static final char HIGH = 'H';
        public static final char LOW = 'L';
        public static final char MEDIUM = 'M';
    }

    // IOIRefID(26): STRING
    public static final class IOIRefID {
        public static final int tag = 26;
    }

    // IOIShares(27): STRING
    public static final class IOIShares {
        public static final int tag = 27;
        public static final String LARGE = "L";
        public static final String MEDIUM = "M";
        public static final String SMALL = "S";
    }

    // IOITransType(28): CHAR
    public static final class IOITransType {
        public static final int tag = 28;
        public static final char CANCEL = 'C';
        public static final char NEW = 'N';
        public static final char REPLACE = 'R';
    }

    // LastCapacity(29): CHAR
    public static final class LastCapacity {
        public static final int tag = 29;
        public static final char AGENT = '1';
        public static final char CROSS_AS_AGENT = '2';
        public static final char CROSS_AS_PRINCIPAL = '3';
        public static final char PRINCIPAL = '4';
    }

    // LastMkt(30): EXCHANGE
    public static final class LastMkt {
        public static final int tag = 30;
    }

    // LastPx(31): PRICE
    public static final class LastPx {
        public static final int tag = 31;
    }

    // LastShares(32): QTY
    public static final class LastShares {
        public static final int tag = 32;
    }

    // LinesOfText(33): INT
    public static final class LinesOfText {
        public static final int tag = 33;
    }

    // MsgSeqNum(34): INT
    public static final class MsgSeqNum {
        public static final int tag = 34;
    }

    // MsgType(35): STRING
    public static final class MsgType {
        public static final int tag = 35;
        public static final String HEARTBEAT = "0";
        public static final String TEST_REQUEST = "1";
        public static final String RESEND_REQUEST = "2";
        public static final String REJECT = "3";
        public static final String SEQUENCE_RESET = "4";
        public static final String LOGOUT = "5";
        public static final String INDICATION_OF_INTEREST = "6";
        public static final String ADVERTISEMENT = "7";
        public static final String EXECUTION_REPORT = "8";
        public static final String ORDER_CANCEL_REJECT = "9";
        public static final String QUOTE_STATUS_REQUEST = "a";
        public static final String LOGON = "A";
        public static final String NEWS = "B";
        public static final String QUOTE_ACKNOWLEDGEMENT = "b";
        public static final String EMAIL = "C";
        public static final String SECURITY_DEFINITION_REQUEST = "c";
        public static final String ORDER_SINGLE = "D";
        public static final String SECURITY_DEFINITION = "d";
        public static final String ORDER_LIST = "E";
        public static final String SECURITY_STATUS_REQUEST = "e";
        public static final String SECURITY_STATUS = "f";
        public static final String ORDER_CANCEL_REQUEST = "F";
        public static final String ORDER_CANCEL_REPLACE_REQUEST = "G";
        public static final String TRADING_SESSION_STATUS_REQUEST = "g";
        public static final String ORDER_STATUS_REQUEST = "H";
        public static final String TRADING_SESSION_STATUS = "h";
        public static final String MASS_QUOTE = "i";
        public static final String BUSINESS_MESSAGE_REJECT = "j";
        public static final String ALLOCATION = "J";
        public static final String LIST_CANCEL_REQUEST = "K";
        public static final String BID_REQUEST = "k";
        public static final String BID_RESPONSE = "l";
        public static final String LIST_EXECUTE = "L";
        public static final String LIST_STRIKE_PRICE = "m";
        public static final String LIST_STATUS_REQUEST = "M";
        public static final String LIST_STATUS = "N";
        public static final String ALLOCATION_ACK = "P";
        public static final String DONT_KNOW_TRADE = "Q";
        public static final String QUOTE_REQUEST = "R";
        public static final String QUOTE = "S";
        public static final String SETTLEMENT_INSTRUCTIONS = "T";
        public static final String MARKET_DATA_REQUEST = "V";
        public static final String MARKET_DATA_SNAPSHOT_FULL_REFRESH = "W";
        public static final String MARKET_DATA_INCREMENTAL_REFRESH = "X";
        public static final String MARKET_DATA_REQUEST_REJECT = "Y";
        public static final String QUOTE_CANCEL = "Z";
    }

    // NewSeqNo(36): INT
    public static final class NewSeqNo {
        public static final int tag = 36;
    }

    // OrderID(37): STRING
    public static final class OrderID {
        public static final int tag = 37;
    }

    // OrderQty(38): QTY
    public static final class OrderQty {
        public static final int tag = 38;
    }

    // OrdStatus(39): CHAR
    public static final class OrdStatus {
        public static final int tag = 39;
        public static final char NEW = '0';
        public static final char PARTIALLY_FILLED = '1';
        public static final char FILLED = '2';
        public static final char DONE_FOR_DAY = '3';
        public static final char CANCELED = '4';
        public static final char REPLACED = '5';
        public static final char PENDING_CANCEL = '6';
        public static final char STOPPED = '7';
        public static final char REJECTED = '8';
        public static final char SUSPENDED = '9';
        public static final char PENDING_NEW = 'A';
        public static final char CALCULATED = 'B';
        public static final char EXPIRED = 'C';
        public static final char ACCEPTED_FOR_BIDDING = 'D';
        public static final char PENDING_REPLACE = 'E';
    }

    // OrdType(40): CHAR
    public static final class OrdType {
        public static final int tag = 40;
        public static final char MARKET = '1';
        public static final char LIMIT = '2';
        public static final char STOP = '3';
        public static final char STOP_LIMIT = '4';
        public static final char MARKET_ON_CLOSE = '5';
        public static final char WITH_OR_WITHOUT = '6';
        public static final char LIMIT_OR_BETTER = '7';
        public static final char LIMIT_WITH_OR_WITHOUT = '8';
        public static final char ON_BASIS = '9';
        public static final char ON_CLOSE = 'A';
        public static final char LIMIT_ON_CLOSE = 'B';
        public static final char FOREX_C = 'C';
        public static final char PREVIOUSLY_QUOTED = 'D';
        public static final char PREVIOUSLY_INDICATED = 'E';
        public static final char FOREX_F = 'F';
        public static final char FOREX_G = 'G';
        public static final char FOREX_H = 'H';
        public static final char FUNARI = 'I';
        public static final char PEGGED = 'P';
    }

    // OrigClOrdID(41): STRING
    public static final class OrigClOrdID {
        public static final int tag = 41;
    }

    // OrigTime(42): UTCTIMESTAMP
    public static final class OrigTime {
        public static final int tag = 42;
    }

    // PossDupFlag(43): BOOLEAN
    public static final class PossDupFlag {
        public static final int tag = 43;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // Price(44): PRICE
    public static final class Price {
        public static final int tag = 44;
    }

    // RefSeqNum(45): INT
    public static final class RefSeqNum {
        public static final int tag = 45;
    }

    // RelatdSym(46): STRING
    public static final class RelatdSym {
        public static final int tag = 46;
    }

    // Rule80A(47): CHAR
    public static final class Rule80A {
        public static final int tag = 47;
        public static final char AGENCY_SINGLE_ORDER = 'A';
        public static final char SHORT_EXEMPT_TRANSACTION_B = 'B';
        public static final char PROGRAM_ORDER_NON_INDEX_ARB_FOR_MEMBER_FIRM_ORG = 'C';
        public static final char PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG = 'D';
        public static final char REGISTERED_EQUITY_MARKET_MAKER_TRADES = 'E';
        public static final char SHORT_EXEMPT_TRANSACTION_F = 'F';
        public static final char SHORT_EXEMPT_TRANSACTION_H = 'H';
        public static final char INDIVIDUAL_INVESTOR_SINGLE_ORDER = 'I';
        public static final char PROGRAM_ORDER_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER = 'J';
        public static final char PROGRAM_ORDER_NON_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER = 'K';
        public static final char SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE = 'L';
        public static final char PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER = 'M';
        public static final char PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_MEMBER = 'N';
        public static final char COMPETING_DEALER_TRADES_O = 'O';
        public static final char PRINCIPAL = 'P';
        public static final char COMPETING_DEALER_TRADES_R = 'R';
        public static final char SPECIALIST_TRADES = 'S';
        public static final char COMPETING_DEALER_TRADES_T = 'T';
        public static final char PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_AGENCY = 'U';
        public static final char ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER = 'W';
        public static final char SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE = 'X';
        public static final char PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_AGENCY = 'Y';
        public static final char SHORT_EXEMPT_TRANSACTION_FOR_NON_MEMBER_COMPETING_MARKET_MAKER = 'Z';
    }

    // SecurityID(48): STRING
    public static final class SecurityID {
        public static final int tag = 48;
    }

    // SenderCompID(49): STRING
    public static final class SenderCompID {
        public static final int tag = 49;
    }

    // SenderSubID(50): STRING
    public static final class SenderSubID {
        public static final int tag = 50;
    }

    // SendingDate(51): LOCALMKTDATE
    public static final class SendingDate {
        public static final int tag = 51;
    }

    // SendingTime(52): UTCTIMESTAMP
    public static final class SendingTime {
        public static final int tag = 52;
    }

    // Shares(53): QTY
    public static final class Shares {
        public static final int tag = 53;
    }

    // Side(54): CHAR
    public static final class Side {
        public static final int tag = 54;
        public static final char BUY = '1';
        public static final char SELL = '2';
        public static final char BUY_MINUS = '3';
        public static final char SELL_PLUS = '4';
        public static final char SELL_SHORT = '5';
        public static final char SELL_SHORT_EXEMPT = '6';
        public static final char UNDISCLOSED = '7';
        public static final char CROSS = '8';
        public static final char CROSS_SHORT = '9';
    }

    // Symbol(55): STRING
    public static final class Symbol {
        public static final int tag = 55;
    }

    // TargetCompID(56): STRING
    public static final class TargetCompID {
        public static final int tag = 56;
    }

    // TargetSubID(57): STRING
    public static final class TargetSubID {
        public static final int tag = 57;
    }

    // Text(58): STRING
    public static final class Text {
        public static final int tag = 58;
    }

    // TimeInForce(59): CHAR
    public static final class TimeInForce {
        public static final int tag = 59;
        public static final char DAY = '0';
        public static final char GOOD_TILL_CANCEL = '1';
        public static final char AT_THE_OPENING = '2';
        public static final char IMMEDIATE_OR_CANCEL = '3';
        public static final char FILL_OR_KILL = '4';
        public static final char GOOD_TILL_CROSSING = '5';
        public static final char GOOD_TILL_DATE = '6';
    }

    // TransactTime(60): UTCTIMESTAMP
    public static final class TransactTime {
        public static final int tag = 60;
    }

    // Urgency(61): CHAR
    public static final class Urgency {
        public static final int tag = 61;
        public static final char NORMAL = '0';
        public static final char FLASH = '1';
        public static final char BACKGROUND = '2';
    }

    // ValidUntilTime(62): UTCTIMESTAMP
    public static final class ValidUntilTime {
        public static final int tag = 62;
    }

    // SettlmntTyp(63): CHAR
    public static final class SettlmntTyp {
        public static final int tag = 63;
        public static final char REGULAR = '0';
        public static final char CASH = '1';
        public static final char NEXT_DAY = '2';
        public static final char T_PLUS_2 = '3';
        public static final char T_PLUS_3 = '4';
        public static final char T_PLUS_4 = '5';
        public static final char FUTURE = '6';
        public static final char WHEN_ISSUED = '7';
        public static final char SELLERS_OPTION = '8';
        public static final char T_PLUS_5 = '9';
    }

    // FutSettDate(64): LOCALMKTDATE
    public static final class FutSettDate {
        public static final int tag = 64;
    }

    // SymbolSfx(65): STRING
    public static final class SymbolSfx {
        public static final int tag = 65;
    }

    // ListID(66): STRING
    public static final class ListID {
        public static final int tag = 66;
    }

    // ListSeqNo(67): INT
    public static final class ListSeqNo {
        public static final int tag = 67;
    }

    // TotNoOrders(68): INT
    public static final class TotNoOrders {
        public static final int tag = 68;
    }

    // ListExecInst(69): STRING
    public static final class ListExecInst {
        public static final int tag = 69;
    }

    // AllocID(70): STRING
    public static final class AllocID {
        public static final int tag = 70;
    }

    // AllocTransType(71): CHAR
    public static final class AllocTransType {
        public static final int tag = 71;
        public static final char NEW = '0';
        public static final char REPLACE = '1';
        public static final char CANCEL = '2';
        public static final char PRELIMINARY = '3';
        public static final char CALCULATED = '4';
        public static final char CALCULATED_WITHOUT_PRELIMINARY = '5';
    }

    // RefAllocID(72): STRING
    public static final class RefAllocID {
        public static final int tag = 72;
    }

    // NoOrders(73): INT
    public static final class NoOrders {
        public static final int tag = 73;
    }

    // AvgPrxPrecision(74): INT
    public static final class AvgPrxPrecision {
        public static final int tag = 74;
    }

    // TradeDate(75): LOCALMKTDATE
    public static final class TradeDate {
        public static final int tag = 75;
    }

    // ExecBroker(76): STRING
    public static final class ExecBroker {
        public static final int tag = 76;
    }

    // OpenClose(77): CHAR
    public static final class OpenClose {
        public static final int tag = 77;
        public static final char CLOSE = 'C';
        public static final char OPEN = 'O';
    }

    // NoAllocs(78): INT
    public static final class NoAllocs {
        public static final int tag = 78;
    }

    // AllocAccount(79): STRING
    public static final class AllocAccount {
        public static final int tag = 79;
    }

    // AllocShares(80): QTY
    public static final class AllocShares {
        public static final int tag = 80;
    }

    // ProcessCode(81): CHAR
    public static final class ProcessCode {
        public static final int tag = 81;
        public static final char REGULAR = '0';
        public static final char SOFT_DOLLAR = '1';
        public static final char STEP_IN = '2';
        public static final char STEP_OUT = '3';
        public static final char SOFT_DOLLAR_STEP_IN = '4';
        public static final char SOFT_DOLLAR_STEP_OUT = '5';
        public static final char PLAN_SPONSOR = '6';
    }

    // NoRpts(82): INT
    public static final class NoRpts {
        public static final int tag = 82;
    }

    // RptSeq(83): INT
    public static final class RptSeq {
        public static final int tag = 83;
    }

    // CxlQty(84): QTY
    public static final class CxlQty {
        public static final int tag = 84;
    }

    // NoDlvyInst(85): INT
    public static final class NoDlvyInst {
        public static final int tag = 85;
    }

    // DlvyInst(86): STRING
    public static final class DlvyInst {
        public static final int tag = 86;
    }

    // AllocStatus(87): INT
    public static final class AllocStatus {
        public static final int tag = 87;
        public static final int ACCEPTED = 0;
        public static final int REJECTED = 1;
        public static final int PARTIAL_ACCEPT = 2;
        public static final int RECEIVED = 3;
    }

    // AllocRejCode(88): INT
    public static final class AllocRejCode {
        public static final int tag = 88;
        public static final int UNKNOWN_ACCOUNT = 0;
        public static final int INCORRECT_QUANTITY = 1;
        public static final int INCORRECT_AVERAGE_PRICE = 2;
        public static final int UNKNOWN_EXECUTING_BROKER_MNEMONIC = 3;
        public static final int COMMISSION_DIFFERENCE = 4;
        public static final int UNKNOWN_ORDERID = 5;
        public static final int UNKNOWN_LISTID = 6;
        public static final int OTHER = 7;
    }

    // Signature(89): DATA
    public static final class Signature {
        public static final int tag = 89;
    }

    // SecureDataLen(90): LENGTH
    public static final class SecureDataLen {
        public static final int tag = 90;
    }

    // SecureData(91): DATA
    public static final class SecureData {
        public static final int tag = 91;
    }

    // BrokerOfCredit(92): STRING
    public static final class BrokerOfCredit {
        public static final int tag = 92;
    }

    // SignatureLength(93): LENGTH
    public static final class SignatureLength {
        public static final int tag = 93;
    }

    // EmailType(94): CHAR
    public static final class EmailType {
        public static final int tag = 94;
        public static final char NEW = '0';
        public static final char REPLY = '1';
        public static final char ADMIN_REPLY = '2';
    }

    // RawDataLength(95): LENGTH
    public static final class RawDataLength {
        public static final int tag = 95;
    }

    // RawData(96): DATA
    public static final class RawData {
        public static final int tag = 96;
    }

    // PossResend(97): BOOLEAN
    public static final class PossResend {
        public static final int tag = 97;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // EncryptMethod(98): INT
    public static final class EncryptMethod {
        public static final int tag = 98;
        public static final int NONE = 0;
        public static final int PKCS = 1;
        public static final int DES = 2;
        public static final int PKCS_DES = 3;
        public static final int PGP_DES = 4;
        public static final int PGP_DES_MD5 = 5;
        public static final int PEM_DES_MD5 = 6;
    }

    // StopPx(99): PRICE
    public static final class StopPx {
        public static final int tag = 99;
    }

    // ExDestination(100): EXCHANGE
    public static final class ExDestination {
        public static final int tag = 100;
    }

    // CxlRejReason(102): INT
    public static final class CxlRejReason {
        public static final int tag = 102;
        public static final int TOO_LATE_TO_CANCEL = 0;
        public static final int UNKNOWN_ORDER = 1;
        public static final int BROKER_OPTION = 2;
        public static final int ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS = 3;
    }

    // OrdRejReason(103): INT
    public static final class OrdRejReason {
        public static final int tag = 103;
        public static final int BROKER_OPTION = 0;
        public static final int UNKNOWN_SYMBOL = 1;
        public static final int EXCHANGE_CLOSED = 2;
        public static final int ORDER_EXCEEDS_LIMIT = 3;
        public static final int TOO_LATE_TO_ENTER = 4;
        public static final int UNKNOWN_ORDER = 5;
        public static final int DUPLICATE_ORDER = 6;
        public static final int DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER = 7;
        public static final int STALE_ORDER = 8;
    }

    // IOIQualifier(104): CHAR
    public static final class IOIQualifier {
        public static final int tag = 104;
        public static final char ALL_OR_NONE = 'A';
        public static final char AT_THE_CLOSE = 'C';
        public static final char IN_TOUCH_WITH = 'I';
        public static final char LIMIT = 'L';
        public static final char MORE_BEHIND = 'M';
        public static final char AT_THE_OPEN = 'O';
        public static final char TAKING_A_POSITION = 'P';
        public static final char AT_THE_MARKET = 'Q';
        public static final char READY_TO_TRADE = 'R';
        public static final char PORTFOLIO_SHOW_N = 'S';
        public static final char THROUGH_THE_DAY = 'T';
        public static final char VERSUS = 'V';
        public static final char INDICATION = 'W';
        public static final char CROSSING_OPPORTUNITY = 'X';
        public static final char AT_THE_MIDPOINT = 'Y';
        public static final char PRE_OPEN = 'Z';
    }

    // WaveNo(105): STRING
    public static final class WaveNo {
        public static final int tag = 105;
    }

    // Issuer(106): STRING
    public static final class Issuer {
        public static final int tag = 106;
    }

    // SecurityDesc(107): STRING
    public static final class SecurityDesc {
        public static final int tag = 107;
    }

    // HeartBtInt(108): INT
    public static final class HeartBtInt {
        public static final int tag = 108;
    }

    // ClientID(109): STRING
    public static final class ClientID {
        public static final int tag = 109;
    }

    // MinQty(110): QTY
    public static final class MinQty {
        public static final int tag = 110;
    }

    // MaxFloor(111): QTY
    public static final class MaxFloor {
        public static final int tag = 111;
    }

    // TestReqID(112): STRING
    public static final class TestReqID {
        public static final int tag = 112;
    }

    // ReportToExch(113): BOOLEAN
    public static final class ReportToExch {
        public static final int tag = 113;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // LocateReqd(114): BOOLEAN
    public static final class LocateReqd {
        public static final int tag = 114;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // OnBehalfOfCompID(115): STRING
    public static final class OnBehalfOfCompID {
        public static final int tag = 115;
    }

    // OnBehalfOfSubID(116): STRING
    public static final class OnBehalfOfSubID {
        public static final int tag = 116;
    }

    // QuoteID(117): STRING
    public static final class QuoteID {
        public static final int tag = 117;
    }

    // NetMoney(118): AMT
    public static final class NetMoney {
        public static final int tag = 118;
    }

    // SettlCurrAmt(119): AMT
    public static final class SettlCurrAmt {
        public static final int tag = 119;
    }

    // SettlCurrency(120): CURRENCY
    public static final class SettlCurrency {
        public static final int tag = 120;
    }

    // ForexReq(121): BOOLEAN
    public static final class ForexReq {
        public static final int tag = 121;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // OrigSendingTime(122): UTCTIMESTAMP
    public static final class OrigSendingTime {
        public static final int tag = 122;
    }

    // GapFillFlag(123): BOOLEAN
    public static final class GapFillFlag {
        public static final int tag = 123;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // NoExecs(124): INT
    public static final class NoExecs {
        public static final int tag = 124;
    }

    // CxlType(125):  CHAR
    public static final class CxlType {
        public static final int tag = 125;
    }

    // ExpireTime(126): UTCTIMESTAMP
    public static final class ExpireTime {
        public static final int tag = 126;
    }

    // DKReason(127): CHAR
    public static final class DKReason {
        public static final int tag = 127;
        public static final char UNKNOWN_SYMBOL = 'A';
        public static final char WRONG_SIDE = 'B';
        public static final char QUANTITY_EXCEEDS_ORDER = 'C';
        public static final char NO_MATCHING_ORDER = 'D';
        public static final char PRICE_EXCEEDS_LIMIT = 'E';
        public static final char OTHER = 'Z';
    }

    // DeliverToCompID(128): STRING
    public static final class DeliverToCompID {
        public static final int tag = 128;
    }

    // DeliverToSubID(129): STRING
    public static final class DeliverToSubID {
        public static final int tag = 129;
    }

    // IOINaturalFlag(130): BOOLEAN
    public static final class IOINaturalFlag {
        public static final int tag = 130;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // QuoteReqID(131): STRING
    public static final class QuoteReqID {
        public static final int tag = 131;
    }

    // BidPx(132): PRICE
    public static final class BidPx {
        public static final int tag = 132;
    }

    // OfferPx(133): PRICE
    public static final class OfferPx {
        public static final int tag = 133;
    }

    // BidSize(134): QTY
    public static final class BidSize {
        public static final int tag = 134;
    }

    // OfferSize(135): QTY
    public static final class OfferSize {
        public static final int tag = 135;
    }

    // NoMiscFees(136): INT
    public static final class NoMiscFees {
        public static final int tag = 136;
    }

    // MiscFeeAmt(137): AMT
    public static final class MiscFeeAmt {
        public static final int tag = 137;
    }

    // MiscFeeCurr(138): CURRENCY
    public static final class MiscFeeCurr {
        public static final int tag = 138;
    }

    // MiscFeeType(139): CHAR
    public static final class MiscFeeType {
        public static final int tag = 139;
        public static final char REGULATORY = '1';
        public static final char TAX = '2';
        public static final char LOCAL_COMMISSION = '3';
        public static final char EXCHANGE_FEES = '4';
        public static final char STAMP = '5';
        public static final char LEVY = '6';
        public static final char OTHER = '7';
        public static final char MARKUP = '8';
        public static final char CONSUMPTION_TAX = '9';
    }

    // PrevClosePx(140): PRICE
    public static final class PrevClosePx {
        public static final int tag = 140;
    }

    // ResetSeqNumFlag(141): BOOLEAN
    public static final class ResetSeqNumFlag {
        public static final int tag = 141;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // SenderLocationID(142): STRING
    public static final class SenderLocationID {
        public static final int tag = 142;
    }

    // TargetLocationID(143): STRING
    public static final class TargetLocationID {
        public static final int tag = 143;
    }

    // OnBehalfOfLocationID(144): STRING
    public static final class OnBehalfOfLocationID {
        public static final int tag = 144;
    }

    // DeliverToLocationID(145): STRING
    public static final class DeliverToLocationID {
        public static final int tag = 145;
    }

    // NoRelatedSym(146): INT
    public static final class NoRelatedSym {
        public static final int tag = 146;
    }

    // Subject(147): STRING
    public static final class Subject {
        public static final int tag = 147;
    }

    // Headline(148): STRING
    public static final class Headline {
        public static final int tag = 148;
    }

    // URLLink(149): STRING
    public static final class URLLink {
        public static final int tag = 149;
    }

    // ExecType(150): CHAR
    public static final class ExecType {
        public static final int tag = 150;
        public static final char NEW = '0';
        public static final char PARTIAL_FILL = '1';
        public static final char FILL = '2';
        public static final char DONE_FOR_DAY = '3';
        public static final char CANCELED = '4';
        public static final char REPLACE = '5';
        public static final char PENDING_CANCEL = '6';
        public static final char STOPPED = '7';
        public static final char REJECTED = '8';
        public static final char SUSPENDED = '9';
        public static final char PENDING_NEW = 'A';
        public static final char CALCULATED = 'B';
        public static final char EXPIRED = 'C';
        public static final char RESTATED = 'D';
        public static final char PENDING_REPLACE = 'E';
    }

    // LeavesQty(151): QTY
    public static final class LeavesQty {
        public static final int tag = 151;
    }

    // CashOrderQty(152): QTY
    public static final class CashOrderQty {
        public static final int tag = 152;
    }

    // AllocAvgPx(153): PRICE
    public static final class AllocAvgPx {
        public static final int tag = 153;
    }

    // AllocNetMoney(154): AMT
    public static final class AllocNetMoney {
        public static final int tag = 154;
    }

    // SettlCurrFxRate(155): FLOAT
    public static final class SettlCurrFxRate {
        public static final int tag = 155;
    }

    // SettlCurrFxRateCalc(156): CHAR
    public static final class SettlCurrFxRateCalc {
        public static final int tag = 156;
        public static final char MULTIPLY = 'M';
        public static final char DIVIDE = 'D';
    }

    // NumDaysInterest(157): INT
    public static final class NumDaysInterest {
        public static final int tag = 157;
    }

    // AccruedInterestRate(158): FLOAT
    public static final class AccruedInterestRate {
        public static final int tag = 158;
    }

    // AccruedInterestAmt(159): AMT
    public static final class AccruedInterestAmt {
        public static final int tag = 159;
    }

    // SettlInstMode(160): CHAR
    public static final class SettlInstMode {
        public static final int tag = 160;
        public static final char DEFAULT = '0';
        public static final char STANDING_INSTRUCTIONS_PROVIDED = '1';
        public static final char SPECIFIC_ALLOCATION_ACCOUNT_OVERRIDING = '2';
        public static final char SPECIFIC_ALLOCATION_ACCOUNT_STANDING = '3';
    }

    // AllocText(161): STRING
    public static final class AllocText {
        public static final int tag = 161;
    }

    // SettlInstID(162): STRING
    public static final class SettlInstID {
        public static final int tag = 162;
    }

    // SettlInstTransType(163): CHAR
    public static final class SettlInstTransType {
        public static final int tag = 163;
        public static final char CANCEL = 'C';
        public static final char NEW = 'N';
        public static final char REPLACE = 'R';
    }

    // EmailThreadID(164): STRING
    public static final class EmailThreadID {
        public static final int tag = 164;
    }

    // SettlInstSource(165): CHAR
    public static final class SettlInstSource {
        public static final int tag = 165;
        public static final char BROKERS_INSTRUCTIONS = '1';
        public static final char INSTITUTIONS_INSTRUCTIONS = '2';
    }

    // SettlLocation(166): STRING
    public static final class SettlLocation {
        public static final int tag = 166;
        public static final String CEDEL = "CED";
        public static final String DEPOSITORY_TRUST_COMPANY = "DTC";
        public static final String EUROCLEAR = "EUR";
        public static final String FEDERAL_BOOK_ENTRY = "FED";
        public static final String LOCAL_MARKET_SETTLE_LOCATION = "ISO Country Code";
        public static final String PHYSICAL = "PNY";
        public static final String PARTICIPANT_TRUST_COMPANY = "PTC";
    }

    // SecurityType(167): STRING
    public static final class SecurityType {
        public static final int tag = 167;
        public static final String WILDCARD_ENTRY = "?";
        public static final String BANKERS_ACCEPTANCE = "BA";
        public static final String CONVERTIBLE_BOND = "CB";
        public static final String CERTIFICATE_OF_DEPOSIT = "CD";
        public static final String COLLATERALIZE_MORTGAGE_OBLIGATION = "CMO";
        public static final String CORPORATE_BOND = "CORP";
        public static final String COMMERCIAL_PAPER = "CP";
        public static final String CORPORATE_PRIVATE_PLACEMENT = "CPP";
        public static final String COMMON_STOCK = "CS";
        public static final String FEDERAL_HOUSING_AUTHORITY = "FHA";
        public static final String FEDERAL_HOME_LOAN = "FHL";
        public static final String FEDERAL_NATIONAL_MORTGAGE_ASSOCIATION = "FN";
        public static final String FOREIGN_EXCHANGE_CONTRACT = "FOR";
        public static final String FUTURE = "FUT";
        public static final String GOVERNMENT_NATIONAL_MORTGAGE_ASSOCIATION = "GN";
        public static final String TREASURIES_PLUS_AGENCY_DEBENTURE = "GOVT";
        public static final String MORTGAGE_IOETTE = "IET";
        public static final String MUTUAL_FUND = "MF";
        public static final String MORTGAGE_INTEREST_ONLY = "MIO";
        public static final String MORTGAGE_PRINCIPAL_ONLY = "MPO";
        public static final String MORTGAGE_PRIVATE_PLACEMENT = "MPP";
        public static final String MISCELLANEOUS_PASS_THRU = "MPT";
        public static final String MUNICIPAL_BOND = "MUNI";
        public static final String NO_ISITC_SECURITY_TYPE = "NONE";
        public static final String OPTION = "OPT";
        public static final String PREFERRED_STOCK = "PS";
        public static final String REPURCHASE_AGREEMENT = "RP";
        public static final String REVERSE_REPURCHASE_AGREEMENT = "RVRP";
        public static final String STUDENT_LOAN_MARKETING_ASSOCIATION = "SL";
        public static final String TIME_DEPOSIT = "TD";
        public static final String US_TREASURY_BILL = "USTB";
        public static final String WARRANT = "WAR";
        public static final String CATS_TIGERS_LIONS = "ZOO";
    }

    // EffectiveTime(168): UTCTIMESTAMP
    public static final class EffectiveTime {
        public static final int tag = 168;
    }

    // StandInstDbType(169): INT
    public static final class StandInstDbType {
        public static final int tag = 169;
        public static final int OTHER = 0;
        public static final int DTC_SID = 1;
        public static final int THOMSON_ALERT = 2;
        public static final int A_GLOBAL_CUSTODIAN = 3;
    }

    // StandInstDbName(170): STRING
    public static final class StandInstDbName {
        public static final int tag = 170;
    }

    // StandInstDbID(171): STRING
    public static final class StandInstDbID {
        public static final int tag = 171;
    }

    // SettlDeliveryType(172): INT
    public static final class SettlDeliveryType {
        public static final int tag = 172;
    }

    // SettlDepositoryCode(173): STRING
    public static final class SettlDepositoryCode {
        public static final int tag = 173;
    }

    // SettlBrkrCode(174): STRING
    public static final class SettlBrkrCode {
        public static final int tag = 174;
    }

    // SettlInstCode(175): STRING
    public static final class SettlInstCode {
        public static final int tag = 175;
    }

    // SecuritySettlAgentName(176): STRING
    public static final class SecuritySettlAgentName {
        public static final int tag = 176;
    }

    // SecuritySettlAgentCode(177): STRING
    public static final class SecuritySettlAgentCode {
        public static final int tag = 177;
    }

    // SecuritySettlAgentAcctNum(178): STRING
    public static final class SecuritySettlAgentAcctNum {
        public static final int tag = 178;
    }

    // SecuritySettlAgentAcctName(179): STRING
    public static final class SecuritySettlAgentAcctName {
        public static final int tag = 179;
    }

    // SecuritySettlAgentContactName(180): STRING
    public static final class SecuritySettlAgentContactName {
        public static final int tag = 180;
    }

    // SecuritySettlAgentContactPhone(181): STRING
    public static final class SecuritySettlAgentContactPhone {
        public static final int tag = 181;
    }

    // CashSettlAgentName(182): STRING
    public static final class CashSettlAgentName {
        public static final int tag = 182;
    }

    // CashSettlAgentCode(183): STRING
    public static final class CashSettlAgentCode {
        public static final int tag = 183;
    }

    // CashSettlAgentAcctNum(184): STRING
    public static final class CashSettlAgentAcctNum {
        public static final int tag = 184;
    }

    // CashSettlAgentAcctName(185): STRING
    public static final class CashSettlAgentAcctName {
        public static final int tag = 185;
    }

    // CashSettlAgentContactName(186): STRING
    public static final class CashSettlAgentContactName {
        public static final int tag = 186;
    }

    // CashSettlAgentContactPhone(187): STRING
    public static final class CashSettlAgentContactPhone {
        public static final int tag = 187;
    }

    // BidSpotRate(188): PRICE
    public static final class BidSpotRate {
        public static final int tag = 188;
    }

    // BidForwardPoints(189): PRICEOFFSET
    public static final class BidForwardPoints {
        public static final int tag = 189;
    }

    // OfferSpotRate(190): PRICE
    public static final class OfferSpotRate {
        public static final int tag = 190;
    }

    // OfferForwardPoints(191): PRICEOFFSET
    public static final class OfferForwardPoints {
        public static final int tag = 191;
    }

    // OrderQty2(192): QTY
    public static final class OrderQty2 {
        public static final int tag = 192;
    }

    // FutSettDate2(193): LOCALMKTDATE
    public static final class FutSettDate2 {
        public static final int tag = 193;
    }

    // LastSpotRate(194): PRICE
    public static final class LastSpotRate {
        public static final int tag = 194;
    }

    // LastForwardPoints(195): PRICEOFFSET
    public static final class LastForwardPoints {
        public static final int tag = 195;
    }

    // AllocLinkID(196): STRING
    public static final class AllocLinkID {
        public static final int tag = 196;
    }

    // AllocLinkType(197): INT
    public static final class AllocLinkType {
        public static final int tag = 197;
        public static final int F_X_NETTING = 0;
        public static final int F_X_SWAP = 1;
    }

    // SecondaryOrderID(198): STRING
    public static final class SecondaryOrderID {
        public static final int tag = 198;
    }

    // NoIOIQualifiers(199): INT
    public static final class NoIOIQualifiers {
        public static final int tag = 199;
    }

    // MaturityMonthYear(200): MONTHYEAR
    public static final class MaturityMonthYear {
        public static final int tag = 200;
    }

    // PutOrCall(201): INT
    public static final class PutOrCall {
        public static final int tag = 201;
        public static final int PUT = 0;
        public static final int CALL = 1;
    }

    // StrikePrice(202): PRICE
    public static final class StrikePrice {
        public static final int tag = 202;
    }

    // CoveredOrUncovered(203): INT
    public static final class CoveredOrUncovered {
        public static final int tag = 203;
        public static final int COVERED = 0;
        public static final int UNCOVERED = 1;
    }

    // CustomerOrFirm(204): INT
    public static final class CustomerOrFirm {
        public static final int tag = 204;
        public static final int CUSTOMER = 0;
        public static final int FIRM = 1;
    }

    // MaturityDay(205): DAYOFMONTH
    public static final class MaturityDay {
        public static final int tag = 205;
    }

    // OptAttribute(206): CHAR
    public static final class OptAttribute {
        public static final int tag = 206;
    }

    // SecurityExchange(207): EXCHANGE
    public static final class SecurityExchange {
        public static final int tag = 207;
    }

    // NotifyBrokerOfCredit(208): BOOLEAN
    public static final class NotifyBrokerOfCredit {
        public static final int tag = 208;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // AllocHandlInst(209): INT
    public static final class AllocHandlInst {
        public static final int tag = 209;
        public static final int MATCH = 1;
        public static final int FORWARD = 2;
        public static final int FORWARD_AND_MATCH = 3;
    }

    // MaxShow(210): QTY
    public static final class MaxShow {
        public static final int tag = 210;
    }

    // PegDifference(211): PRICEOFFSET
    public static final class PegDifference {
        public static final int tag = 211;
    }

    // XmlDataLen(212): LENGTH
    public static final class XmlDataLen {
        public static final int tag = 212;
    }

    // XmlData(213): DATA
    public static final class XmlData {
        public static final int tag = 213;
    }

    // SettlInstRefID(214): STRING
    public static final class SettlInstRefID {
        public static final int tag = 214;
    }

    // NoRoutingIDs(215): INT
    public static final class NoRoutingIDs {
        public static final int tag = 215;
    }

    // RoutingType(216): INT
    public static final class RoutingType {
        public static final int tag = 216;
        public static final int TARGET_FIRM = 1;
        public static final int TARGET_LIST = 2;
        public static final int BLOCK_FIRM = 3;
        public static final int BLOCK_LIST = 4;
    }

    // RoutingID(217): STRING
    public static final class RoutingID {
        public static final int tag = 217;
    }

    // SpreadToBenchmark(218): PRICEOFFSET
    public static final class SpreadToBenchmark {
        public static final int tag = 218;
    }

    // Benchmark(219): CHAR
    public static final class Benchmark {
        public static final int tag = 219;
        public static final char CURVE = '1';
        public static final char _5_YR = '2';
        public static final char OLD_5 = '3';
        public static final char _10_YR = '4';
        public static final char OLD_10 = '5';
        public static final char _30_YR = '6';
        public static final char OLD_30 = '7';
        public static final char _3_MO_LIBOR = '8';
        public static final char _6_MO_LIBOR = '9';
    }

    // CouponRate(223): FLOAT
    public static final class CouponRate {
        public static final int tag = 223;
    }

    // ContractMultiplier(231): FLOAT
    public static final class ContractMultiplier {
        public static final int tag = 231;
    }

    // MDReqID(262): STRING
    public static final class MDReqID {
        public static final int tag = 262;
    }

    // SubscriptionRequestType(263): CHAR
    public static final class SubscriptionRequestType {
        public static final int tag = 263;
        public static final char SNAPSHOT = '0';
        public static final char SNAPSHOT_PLUS_UPDATES = '1';
        public static final char DISABLE_PREVIOUS_SNAPSHOT_PLUS_UPDATE_REQUEST = '2';
    }

    // MarketDepth(264): INT
    public static final class MarketDepth {
        public static final int tag = 264;
    }

    // MDUpdateType(265): INT
    public static final class MDUpdateType {
        public static final int tag = 265;
        public static final int FULL_REFRESH = 0;
        public static final int INCREMENTAL_REFRESH = 1;
    }

    // AggregatedBook(266): BOOLEAN
    public static final class AggregatedBook {
        public static final int tag = 266;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // NoMDEntryTypes(267): INT
    public static final class NoMDEntryTypes {
        public static final int tag = 267;
    }

    // NoMDEntries(268): INT
    public static final class NoMDEntries {
        public static final int tag = 268;
    }

    // MDEntryType(269): CHAR
    public static final class MDEntryType {
        public static final int tag = 269;
        public static final char BID = '0';
        public static final char OFFER = '1';
        public static final char TRADE = '2';
        public static final char INDEX_VALUE = '3';
        public static final char OPENING_PRICE = '4';
        public static final char CLOSING_PRICE = '5';
        public static final char SETTLEMENT_PRICE = '6';
        public static final char TRADING_SESSION_HIGH_PRICE = '7';
        public static final char TRADING_SESSION_LOW_PRICE = '8';
        public static final char TRADING_SESSION_VWAP_PRICE = '9';
    }

    // MDEntryPx(270): PRICE
    public static final class MDEntryPx {
        public static final int tag = 270;
    }

    // MDEntrySize(271): QTY
    public static final class MDEntrySize {
        public static final int tag = 271;
    }

    // MDEntryDate(272): UTCDATE
    public static final class MDEntryDate {
        public static final int tag = 272;
    }

    // MDEntryTime(273): UTCTIMEONLY
    public static final class MDEntryTime {
        public static final int tag = 273;
    }

    // TickDirection(274): CHAR
    public static final class TickDirection {
        public static final int tag = 274;
        public static final char PLUS_TICK = '0';
        public static final char ZERO_PLUS_TICK = '1';
        public static final char MINUS_TICK = '2';
        public static final char ZERO_MINUS_TICK = '3';
    }

    // MDMkt(275): EXCHANGE
    public static final class MDMkt {
        public static final int tag = 275;
    }

    // QuoteCondition(276): MULTIPLEVALUESTRING
    public static final class QuoteCondition {
        public static final int tag = 276;
        public static final String OPEN = "A";
        public static final String CLOSED = "B";
        public static final String EXCHANGE_BEST = "C";
        public static final String CONSOLIDATED_BEST = "D";
        public static final String LOCKED = "E";
        public static final String CROSSED = "F";
        public static final String DEPTH = "G";
        public static final String FAST_TRADING = "H";
        public static final String NON_FIRM = "I";
    }

    // TradeCondition(277): MULTIPLEVALUESTRING
    public static final class TradeCondition {
        public static final int tag = 277;
        public static final String CASH = "A";
        public static final String AVERAGE_PRICE_TRADE = "B";
        public static final String CASH_TRADE = "C";
        public static final String NEXT_DAY = "D";
        public static final String OPENING = "E";
        public static final String INTRADAY_TRADE_DETAIL = "F";
        public static final String RULE_127_TRADE = "G";
        public static final String RULE_155_TRADE = "H";
        public static final String SOLD_LAST = "I";
        public static final String NEXT_DAY_TRADE = "J";
        public static final String OPENED = "K";
        public static final String SELLER = "L";
        public static final String SOLD = "M";
        public static final String STOPPED_STOCK = "N";
    }

    // MDEntryID(278): STRING
    public static final class MDEntryID {
        public static final int tag = 278;
    }

    // MDUpdateAction(279): CHAR
    public static final class MDUpdateAction {
        public static final int tag = 279;
        public static final char NEW = '0';
        public static final char CHANGE = '1';
        public static final char DELETE = '2';
    }

    // MDEntryRefID(280): STRING
    public static final class MDEntryRefID {
        public static final int tag = 280;
    }

    // MDReqRejReason(281): CHAR
    public static final class MDReqRejReason {
        public static final int tag = 281;
        public static final char UNKNOWN_SYMBOL = '0';
        public static final char DUPLICATE_MDREQID = '1';
        public static final char INSUFFICIENT_BANDWIDTH = '2';
        public static final char INSUFFICIENT_PERMISSIONS = '3';
        public static final char UNSUPPORTED_SUBSCRIPTIONREQUESTTYPE = '4';
        public static final char UNSUPPORTED_MARKETDEPTH = '5';
        public static final char UNSUPPORTED_MDUPDATETYPE = '6';
        public static final char UNSUPPORTED_AGGREGATEDBOOK = '7';
        public static final char UNSUPPORTED_MDENTRYTYPE = '8';
    }

    // MDEntryOriginator(282): STRING
    public static final class MDEntryOriginator {
        public static final int tag = 282;
    }

    // LocationID(283): STRING
    public static final class LocationID {
        public static final int tag = 283;
    }

    // DeskID(284): STRING
    public static final class DeskID {
        public static final int tag = 284;
    }

    // DeleteReason(285): CHAR
    public static final class DeleteReason {
        public static final int tag = 285;
        public static final char CANCELATION = '0';
        public static final char ERROR = '1';
    }

    // OpenCloseSettleFlag(286): CHAR
    public static final class OpenCloseSettleFlag {
        public static final int tag = 286;
        public static final char DAILY_OPEN = '0';
        public static final char SESSION_OPEN = '1';
        public static final char DELIVERY_SETTLEMENT_PRICE = '2';
    }

    // SellerDays(287): INT
    public static final class SellerDays {
        public static final int tag = 287;
    }

    // MDEntryBuyer(288): STRING
    public static final class MDEntryBuyer {
        public static final int tag = 288;
    }

    // MDEntrySeller(289): STRING
    public static final class MDEntrySeller {
        public static final int tag = 289;
    }

    // MDEntryPositionNo(290): INT
    public static final class MDEntryPositionNo {
        public static final int tag = 290;
    }

    // FinancialStatus(291): CHAR
    public static final class FinancialStatus {
        public static final int tag = 291;
        public static final char BANKRUPT = '1';
    }

    // CorporateAction(292): CHAR
    public static final class CorporateAction {
        public static final int tag = 292;
        public static final char EX_DIVIDEND = 'A';
        public static final char EX_DISTRIBUTION = 'B';
        public static final char EX_RIGHTS = 'C';
        public static final char NEW = 'D';
        public static final char EX_INTEREST = 'E';
    }

    // DefBidSize(293): QTY
    public static final class DefBidSize {
        public static final int tag = 293;
    }

    // DefOfferSize(294): QTY
    public static final class DefOfferSize {
        public static final int tag = 294;
    }

    // NoQuoteEntries(295): INT
    public static final class NoQuoteEntries {
        public static final int tag = 295;
    }

    // NoQuoteSets(296): INT
    public static final class NoQuoteSets {
        public static final int tag = 296;
    }

    // QuoteAckStatus(297): INT
    public static final class QuoteAckStatus {
        public static final int tag = 297;
        public static final int ACCEPTED = 0;
        public static final int CANCELED_FOR_SYMBOL = 1;
        public static final int CANCELED_FOR_SECURITY_TYPE = 2;
        public static final int CANCELED_FOR_UNDERLYING = 3;
        public static final int CANCELED_ALL = 4;
        public static final int REJECTED = 5;
    }

    // QuoteCancelType(298): INT
    public static final class QuoteCancelType {
        public static final int tag = 298;
        public static final int CANCEL_FOR_SYMBOL = 1;
        public static final int CANCEL_FOR_SECURITY_TYPE = 2;
        public static final int CANCEL_FOR_UNDERLYING_SYMBOL = 3;
        public static final int CANCEL_FOR_ALL_QUOTES = 4;
    }

    // QuoteEntryID(299): STRING
    public static final class QuoteEntryID {
        public static final int tag = 299;
    }

    // QuoteRejectReason(300): INT
    public static final class QuoteRejectReason {
        public static final int tag = 300;
        public static final int UNKNOWN_SYMBOL = 1;
        public static final int EXCHANGE = 2;
        public static final int QUOTE_REQUEST_EXCEEDS_LIMIT = 3;
        public static final int TOO_LATE_TO_ENTER = 4;
        public static final int UNKNOWN_QUOTE = 5;
        public static final int DUPLICATE_QUOTE = 6;
        public static final int INVALID_BID_ASK_SPREAD = 7;
        public static final int INVALID_PRICE = 8;
        public static final int NOT_AUTHORIZED_TO_QUOTE_SECURITY = 9;
    }

    // QuoteResponseLevel(301): INT
    public static final class QuoteResponseLevel {
        public static final int tag = 301;
        public static final int NO_ACKNOWLEDGEMENT = 0;
        public static final int ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES = 1;
        public static final int ACKNOWLEDGE_EACH_QUOTE_MESSAGES = 2;
    }

    // QuoteSetID(302): STRING
    public static final class QuoteSetID {
        public static final int tag = 302;
    }

    // QuoteRequestType(303): INT
    public static final class QuoteRequestType {
        public static final int tag = 303;
        public static final int MANUAL = 1;
        public static final int AUTOMATIC = 2;
    }

    // TotQuoteEntries(304): INT
    public static final class TotQuoteEntries {
        public static final int tag = 304;
    }

    // UnderlyingIDSource(305): STRING
    public static final class UnderlyingIDSource {
        public static final int tag = 305;
    }

    // UnderlyingIssuer(306): STRING
    public static final class UnderlyingIssuer {
        public static final int tag = 306;
    }

    // UnderlyingSecurityDesc(307): STRING
    public static final class UnderlyingSecurityDesc {
        public static final int tag = 307;
    }

    // UnderlyingSecurityExchange(308): EXCHANGE
    public static final class UnderlyingSecurityExchange {
        public static final int tag = 308;
    }

    // UnderlyingSecurityID(309): STRING
    public static final class UnderlyingSecurityID {
        public static final int tag = 309;
    }

    // UnderlyingSecurityType(310): STRING
    public static final class UnderlyingSecurityType {
        public static final int tag = 310;
    }

    // UnderlyingSymbol(311): STRING
    public static final class UnderlyingSymbol {
        public static final int tag = 311;
    }

    // UnderlyingSymbolSfx(312): STRING
    public static final class UnderlyingSymbolSfx {
        public static final int tag = 312;
    }

    // UnderlyingMaturityMonthYear(313): MONTHYEAR
    public static final class UnderlyingMaturityMonthYear {
        public static final int tag = 313;
    }

    // UnderlyingMaturityDay(314): DAYOFMONTH
    public static final class UnderlyingMaturityDay {
        public static final int tag = 314;
    }

    // UnderlyingPutOrCall(315): INT
    public static final class UnderlyingPutOrCall {
        public static final int tag = 315;
    }

    // UnderlyingStrikePrice(316): PRICE
    public static final class UnderlyingStrikePrice {
        public static final int tag = 316;
    }

    // UnderlyingOptAttribute(317): CHAR
    public static final class UnderlyingOptAttribute {
        public static final int tag = 317;
    }

    // UnderlyingCurrency(318): CURRENCY
    public static final class UnderlyingCurrency {
        public static final int tag = 318;
    }

    // RatioQty(319): QUANTITY
    public static final class RatioQty {
        public static final int tag = 319;
    }

    // SecurityReqID(320): STRING
    public static final class SecurityReqID {
        public static final int tag = 320;
    }

    // SecurityRequestType(321): INT
    public static final class SecurityRequestType {
        public static final int tag = 321;
        public static final int REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS = 0;
        public static final int REQUEST_SECURITY_IDENTITY_FOR_THE_SPECIFICATIONS_PROVIDED = 1;
        public static final int REQUEST_LIST_SECURITY_TYPES = 2;
        public static final int REQUEST_LIST_SECURITIES = 3;
    }

    // SecurityResponseID(322): STRING
    public static final class SecurityResponseID {
        public static final int tag = 322;
    }

    // SecurityResponseType(323): INT
    public static final class SecurityResponseType {
        public static final int tag = 323;
        public static final int ACCEPT_SECURITY_PROPOSAL_AS_IS = 1;
        public static final int ACCEPT_SECURITY_PROPOSAL_WITH_REVISIONS_AS_INDICATED_IN_THE_MESSAGE = 2;
        public static final int LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST = 3;
        public static final int LIST_OF_SECURITIES_RETURNED_PER_REQUEST = 4;
        public static final int REJECT_SECURITY_PROPOSAL = 5;
        public static final int CAN_NOT_MATCH_SELECTION_CRITERIA = 6;
    }

    // SecurityStatusReqID(324): STRING
    public static final class SecurityStatusReqID {
        public static final int tag = 324;
    }

    // UnsolicitedIndicator(325): BOOLEAN
    public static final class UnsolicitedIndicator {
        public static final int tag = 325;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // SecurityTradingStatus(326): INT
    public static final class SecurityTradingStatus {
        public static final int tag = 326;
        public static final int OPENING_DELAY = 1;
        public static final int MARKET_ON_CLOSE_IMBALANCE_SELL = 10;
        public static final int _11 = 11;
        public static final int NO_MARKET_IMBALANCE = 12;
        public static final int NO_MARKET_ON_CLOSE_IMBALANCE = 13;
        public static final int ITS_PRE_OPENING = 14;
        public static final int NEW_PRICE_INDICATION = 15;
        public static final int TRADE_DISSEMINATION_TIME = 16;
        public static final int READY_TO_TRADE = 17;
        public static final int NOT_AVAILABLE_FOR_TRADING = 18;
        public static final int NOT_TRADED_ON_THIS_MARKET = 19;
        public static final int TRADING_HALT = 2;
        public static final int UNKNOWN_OR_INVALID = 20;
        public static final int RESUME = 3;
        public static final int NO_OPEN_NO_RESUME = 4;
        public static final int PRICE_INDICATION = 5;
        public static final int TRADING_RANGE_INDICATION = 6;
        public static final int MARKET_IMBALANCE_BUY = 7;
        public static final int MARKET_IMBALANCE_SELL = 8;
        public static final int MARKET_ON_CLOSE_IMBALANCE_BUY = 9;
    }

    // HaltReasonChar(327): CHAR
    public static final class HaltReasonChar {
        public static final int tag = 327;
        public static final char NEWS_DISSEMINATION = 'D';
        public static final char ORDER_INFLUX = 'E';
        public static final char ORDER_IMBALANCE = 'I';
        public static final char ADDITIONAL_INFORMATION = 'M';
        public static final char NEWS_PENDING = 'P';
        public static final char EQUIPMENT_CHANGEOVER = 'X';
    }

    // InViewOfCommon(328): BOOLEAN
    public static final class InViewOfCommon {
        public static final int tag = 328;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // DueToRelated(329): BOOLEAN
    public static final class DueToRelated {
        public static final int tag = 329;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // BuyVolume(330): QTY
    public static final class BuyVolume {
        public static final int tag = 330;
    }

    // SellVolume(331): QTY
    public static final class SellVolume {
        public static final int tag = 331;
    }

    // HighPx(332): PRICE
    public static final class HighPx {
        public static final int tag = 332;
    }

    // LowPx(333): PRICE
    public static final class LowPx {
        public static final int tag = 333;
    }

    // Adjustment(334): INT
    public static final class Adjustment {
        public static final int tag = 334;
        public static final int CANCEL = 1;
        public static final int ERROR = 2;
        public static final int CORRECTION = 3;
    }

    // TradSesReqID(335): STRING
    public static final class TradSesReqID {
        public static final int tag = 335;
    }

    // TradingSessionID(336): STRING
    public static final class TradingSessionID {
        public static final int tag = 336;
    }

    // ContraTrader(337): STRING
    public static final class ContraTrader {
        public static final int tag = 337;
    }

    // TradSesMethod(338): INT
    public static final class TradSesMethod {
        public static final int tag = 338;
        public static final int ELECTRONIC = 1;
        public static final int OPEN_OUTCRY = 2;
        public static final int TWO_PARTY = 3;
    }

    // TradSesMode(339): INT
    public static final class TradSesMode {
        public static final int tag = 339;
        public static final int TESTING = 1;
        public static final int SIMULATED = 2;
        public static final int PRODUCTION = 3;
    }

    // TradSesStatus(340): INT
    public static final class TradSesStatus {
        public static final int tag = 340;
        public static final int HALTED = 1;
        public static final int OPEN = 2;
        public static final int CLOSED = 3;
        public static final int PRE_OPEN = 4;
        public static final int PRE_CLOSE = 5;
    }

    // TradSesStartTime(341): UTCTIMESTAMP
    public static final class TradSesStartTime {
        public static final int tag = 341;
    }

    // TradSesOpenTime(342): UTCTIMESTAMP
    public static final class TradSesOpenTime {
        public static final int tag = 342;
    }

    // TradSesPreCloseTime(343): UTCTIMESTAMP
    public static final class TradSesPreCloseTime {
        public static final int tag = 343;
    }

    // TradSesCloseTime(344): UTCTIMESTAMP
    public static final class TradSesCloseTime {
        public static final int tag = 344;
    }

    // TradSesEndTime(345): UTCTIMESTAMP
    public static final class TradSesEndTime {
        public static final int tag = 345;
    }

    // NumberOfOrders(346): INT
    public static final class NumberOfOrders {
        public static final int tag = 346;
    }

    // MessageEncoding(347): STRING
    public static final class MessageEncoding {
        public static final int tag = 347;
        public static final String EUC_JP = "EUC-JP";
        public static final String ISO_2022_JP = "ISO-2022-JP";
        public static final String SHIFT_JIS = "SHIFT_JIS";
        public static final String UTF_8 = "UTF-8";
    }

    // EncodedIssuerLen(348): LENGTH
    public static final class EncodedIssuerLen {
        public static final int tag = 348;
    }

    // EncodedIssuer(349): DATA
    public static final class EncodedIssuer {
        public static final int tag = 349;
    }

    // EncodedSecurityDescLen(350): LENGTH
    public static final class EncodedSecurityDescLen {
        public static final int tag = 350;
    }

    // EncodedSecurityDesc(351): DATA
    public static final class EncodedSecurityDesc {
        public static final int tag = 351;
    }

    // EncodedListExecInstLen(352): LENGTH
    public static final class EncodedListExecInstLen {
        public static final int tag = 352;
    }

    // EncodedListExecInst(353): DATA
    public static final class EncodedListExecInst {
        public static final int tag = 353;
    }

    // EncodedTextLen(354): LENGTH
    public static final class EncodedTextLen {
        public static final int tag = 354;
    }

    // EncodedText(355): DATA
    public static final class EncodedText {
        public static final int tag = 355;
    }

    // EncodedSubjectLen(356): LENGTH
    public static final class EncodedSubjectLen {
        public static final int tag = 356;
    }

    // EncodedSubject(357): DATA
    public static final class EncodedSubject {
        public static final int tag = 357;
    }

    // EncodedHeadlineLen(358): LENGTH
    public static final class EncodedHeadlineLen {
        public static final int tag = 358;
    }

    // EncodedHeadline(359): DATA
    public static final class EncodedHeadline {
        public static final int tag = 359;
    }

    // EncodedAllocTextLen(360): LENGTH
    public static final class EncodedAllocTextLen {
        public static final int tag = 360;
    }

    // EncodedAllocText(361): DATA
    public static final class EncodedAllocText {
        public static final int tag = 361;
    }

    // EncodedUnderlyingIssuerLen(362): LENGTH
    public static final class EncodedUnderlyingIssuerLen {
        public static final int tag = 362;
    }

    // EncodedUnderlyingIssuer(363): DATA
    public static final class EncodedUnderlyingIssuer {
        public static final int tag = 363;
    }

    // EncodedUnderlyingSecurityDescLen(364): LENGTH
    public static final class EncodedUnderlyingSecurityDescLen {
        public static final int tag = 364;
    }

    // EncodedUnderlyingSecurityDesc(365): DATA
    public static final class EncodedUnderlyingSecurityDesc {
        public static final int tag = 365;
    }

    // AllocPrice(366): PRICE
    public static final class AllocPrice {
        public static final int tag = 366;
    }

    // QuoteSetValidUntilTime(367): UTCTIMESTAMP
    public static final class QuoteSetValidUntilTime {
        public static final int tag = 367;
    }

    // QuoteEntryRejectReason(368): INT
    public static final class QuoteEntryRejectReason {
        public static final int tag = 368;
        public static final int UNKNOWN_SYMBOL = 1;
        public static final int EXCHANGE = 2;
        public static final int QUOTE_EXCEEDS_LIMIT = 3;
        public static final int TOO_LATE_TO_ENTER = 4;
        public static final int UNKNOWN_QUOTE = 5;
        public static final int DUPLICATE_QUOTE = 6;
        public static final int INVALID_BID_ASK_SPREAD = 7;
        public static final int INVALID_PRICE = 8;
        public static final int NOT_AUTHORIZED_TO_QUOTE_SECURITY = 9;
    }

    // LastMsgSeqNumProcessed(369): INT
    public static final class LastMsgSeqNumProcessed {
        public static final int tag = 369;
    }

    // OnBehalfOfSendingTime(370): UTCTIMESTAMP
    public static final class OnBehalfOfSendingTime {
        public static final int tag = 370;
    }

    // RefTagID(371): INT
    public static final class RefTagID {
        public static final int tag = 371;
    }

    // RefMsgType(372): STRING
    public static final class RefMsgType {
        public static final int tag = 372;
    }

    // SessionRejectReason(373): INT
    public static final class SessionRejectReason {
        public static final int tag = 373;
        public static final int INVALID_TAG_NUMBER = 0;
        public static final int REQUIRED_TAG_MISSING = 1;
        public static final int SENDINGTIME_ACCURACY_PROBLEM = 10;
        public static final int INVALID_MSGTYPE = 11;
        public static final int TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE = 2;
        public static final int UNDEFINED_TAG = 3;
        public static final int TAG_SPECIFIED_WITHOUT_A_VALUE = 4;
        public static final int VALUE_IS_INCORRECT = 5;
        public static final int INCORRECT_DATA_FORMAT_FOR_VALUE = 6;
        public static final int DECRYPTION_PROBLEM = 7;
        public static final int SIGNATURE_PROBLEM = 8;
        public static final int COMPID_PROBLEM = 9;
    }

    // BidRequestTransType(374): CHAR
    public static final class BidRequestTransType {
        public static final int tag = 374;
        public static final char CANCEL = 'C';
        public static final char NO = 'N';
    }

    // ContraBroker(375): STRING
    public static final class ContraBroker {
        public static final int tag = 375;
    }

    // ComplianceID(376): STRING
    public static final class ComplianceID {
        public static final int tag = 376;
    }

    // SolicitedFlag(377): BOOLEAN
    public static final class SolicitedFlag {
        public static final int tag = 377;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // ExecRestatementReason(378): INT
    public static final class ExecRestatementReason {
        public static final int tag = 378;
        public static final int GT_CORPORATE_ACTION = 0;
        public static final int GT_RENEWAL = 1;
        public static final int VERBAL_CHANGE = 2;
        public static final int REPRICING_OF_ORDER = 3;
        public static final int BROKER_OPTION = 4;
        public static final int PARTIAL_DECLINE_OF_ORDERQTY = 5;
    }

    // BusinessRejectRefID(379): STRING
    public static final class BusinessRejectRefID {
        public static final int tag = 379;
    }

    // BusinessRejectReason(380): INT
    public static final class BusinessRejectReason {
        public static final int tag = 380;
        public static final int OTHER = 0;
        public static final int UNKOWN_ID = 1;
        public static final int UNKNOWN_SECURITY = 2;
        public static final int UNSUPPORTED_MESSAGE_TYPE = 3;
        public static final int APPLICATION_NOT_AVAILABLE = 4;
        public static final int CONDITIONALLY_REQUIRED_FIELD_MISSING = 5;
    }

    // GrossTradeAmt(381): AMT
    public static final class GrossTradeAmt {
        public static final int tag = 381;
    }

    // NoContraBrokers(382): INT
    public static final class NoContraBrokers {
        public static final int tag = 382;
    }

    // MaxMessageSize(383): INT
    public static final class MaxMessageSize {
        public static final int tag = 383;
    }

    // NoMsgTypes(384): INT
    public static final class NoMsgTypes {
        public static final int tag = 384;
    }

    // MsgDirection(385): CHAR
    public static final class MsgDirection {
        public static final int tag = 385;
        public static final char RECEIVE = 'R';
        public static final char SEND = 'S';
    }

    // NoTradingSessions(386): INT
    public static final class NoTradingSessions {
        public static final int tag = 386;
    }

    // TotalVolumeTraded(387): QTY
    public static final class TotalVolumeTraded {
        public static final int tag = 387;
    }

    // DiscretionInst(388): CHAR
    public static final class DiscretionInst {
        public static final int tag = 388;
        public static final char RELATED_TO_DISPLAYED_PRICE = '0';
        public static final char RELATED_TO_MARKET_PRICE = '1';
        public static final char RELATED_TO_PRIMARY_PRICE = '2';
        public static final char RELATED_TO_LOCAL_PRIMARY_PRICE = '3';
        public static final char RELATED_TO_MIDPOINT_PRICE = '4';
        public static final char RELATED_TO_LAST_TRADE_PRICE = '5';
    }

    // DiscretionOffset(389): PRICEOFFSET
    public static final class DiscretionOffset {
        public static final int tag = 389;
    }

    // BidID(390): STRING
    public static final class BidID {
        public static final int tag = 390;
    }

    // ClientBidID(391): STRING
    public static final class ClientBidID {
        public static final int tag = 391;
    }

    // ListName(392): STRING
    public static final class ListName {
        public static final int tag = 392;
    }

    // TotalNumSecurities(393): INT
    public static final class TotalNumSecurities {
        public static final int tag = 393;
    }

    // BidType(394): INT
    public static final class BidType {
        public static final int tag = 394;
    }

    // NumTickets(395): INT
    public static final class NumTickets {
        public static final int tag = 395;
    }

    // SideValue1(396): AMT
    public static final class SideValue1 {
        public static final int tag = 396;
    }

    // SideValue2(397): AMT
    public static final class SideValue2 {
        public static final int tag = 397;
    }

    // NoBidDescriptors(398): INT
    public static final class NoBidDescriptors {
        public static final int tag = 398;
    }

    // BidDescriptorType(399): INT
    public static final class BidDescriptorType {
        public static final int tag = 399;
    }

    // BidDescriptor(400): STRING
    public static final class BidDescriptor {
        public static final int tag = 400;
    }

    // SideValueInd(401): INT
    public static final class SideValueInd {
        public static final int tag = 401;
    }

    // LiquidityPctLow(402): FLOAT
    public static final class LiquidityPctLow {
        public static final int tag = 402;
    }

    // LiquidityPctHigh(403): FLOAT
    public static final class LiquidityPctHigh {
        public static final int tag = 403;
    }

    // LiquidityValue(404): AMT
    public static final class LiquidityValue {
        public static final int tag = 404;
    }

    // EFPTrackingError(405): FLOAT
    public static final class EFPTrackingError {
        public static final int tag = 405;
    }

    // FairValue(406): AMT
    public static final class FairValue {
        public static final int tag = 406;
    }

    // OutsideIndexPct(407): FLOAT
    public static final class OutsideIndexPct {
        public static final int tag = 407;
    }

    // ValueOfFutures(408): AMT
    public static final class ValueOfFutures {
        public static final int tag = 408;
    }

    // LiquidityIndType(409): INT
    public static final class LiquidityIndType {
        public static final int tag = 409;
        public static final int _5_DAY_MOVING_AVERAGE = 1;
        public static final int _20_DAY_MOVING_AVERAGE = 2;
        public static final int NORMAL_MARKET_SIZE = 3;
        public static final int OTHER = 4;
    }

    // WtAverageLiquidity(410): FLOAT
    public static final class WtAverageLiquidity {
        public static final int tag = 410;
    }

    // ExchangeForPhysical(411): BOOLEAN
    public static final class ExchangeForPhysical {
        public static final int tag = 411;
        public static final char NO = 'N';
        public static final char YES = 'Y';
    }

    // OutMainCntryUIndex(412): AMT
    public static final class OutMainCntryUIndex {
        public static final int tag = 412;
    }

    // CrossPercent(413): FLOAT
    public static final class CrossPercent {
        public static final int tag = 413;
    }

    // ProgRptReqs(414): INT
    public static final class ProgRptReqs {
        public static final int tag = 414;
        public static final int BUYSIDE_EXPLICITLY_REQUESTS_STATUS_USING_STATUSREQUEST = 1;
        public static final int SELLSIDE_PERIODICALLY_SENDS_STATUS_USING_LISTSTATUS_PERIOD_OPTIONALLY_SPECIFIED_IN_PROGRESSPERIOD = 2;
        public static final int REAL_TIME_EXECUTION_REPORTS = 3;
    }

    // ProgPeriodInterval(415): INT
    public static final class ProgPeriodInterval {
        public static final int tag = 415;
    }

    // IncTaxInd(416): INT
    public static final class IncTaxInd {
        public static final int tag = 416;
        public static final int NET = 1;
        public static final int GROSS = 2;
    }

    // NumBidders(417): INT
    public static final class NumBidders {
        public static final int tag = 417;
    }

    // TradeType(418): CHAR
    public static final class TradeType {
        public static final int tag = 418;
        public static final char AGENCY = 'A';
        public static final char VWAP_GUARANTEE = 'G';
        public static final char GUARANTEED_CLOSE = 'J';
        public static final char RISK_TRADE = 'R';
    }

    // BasisPxType(419): CHAR
    public static final class BasisPxType {
        public static final int tag = 419;
        public static final char CLOSING_PRICE_AT_MORNING_SESSION = '2';
        public static final char CLOSING_PRICE = '3';
        public static final char CURRENT_PRICE = '4';
        public static final char SQ = '5';
        public static final char VWAP_THROUGH_A_DAY = '6';
        public static final char VWAP_THROUGH_A_MORNING_SESSION = '7';
        public static final char VWAP_THROUGH_AN_AFTERNOON_SESSION = '8';
        public static final char VWAP_THROUGH_A_DAY_EXCEPT_YORI = '9';
        public static final char VWAP_THROUGH_A_MORNING_SESSION_EXCEPT_YORI = 'A';
        public static final char VWAP_THROUGH_AN_AFTERNOON_SESSION_EXCEPT_YORI = 'B';
        public static final char STRIKE = 'C';
        public static final char OPEN = 'D';
        public static final char OTHERS = 'Z';
    }

    // NoBidComponents(420): INT
    public static final class NoBidComponents {
        public static final int tag = 420;
    }

    // Country(421): STRING
    public static final class Country {
        public static final int tag = 421;
    }

    // TotNoStrikes(422): INT
    public static final class TotNoStrikes {
        public static final int tag = 422;
    }

    // PriceType(423): INT
    public static final class PriceType {
        public static final int tag = 423;
        public static final int PERCENTAGE = 1;
        public static final int PER_SHARE = 2;
        public static final int FIXED_AMOUNT = 3;
    }

    // DayOrderQty(424): QTY
    public static final class DayOrderQty {
        public static final int tag = 424;
    }

    // DayCumQty(425): QTY
    public static final class DayCumQty {
        public static final int tag = 425;
    }

    // DayAvgPx(426): PRICE
    public static final class DayAvgPx {
        public static final int tag = 426;
    }

    // GTBookingInst(427): INT
    public static final class GTBookingInst {
        public static final int tag = 427;
        public static final int BOOK_OUT_ALL_TRADES_ON_DAY_OF_EXECUTION = 0;
        public static final int ACCUMULATE_EXECUTIONS_UNTIL_ORDER_IS_FILLED_OR_EXPIRES = 1;
        public static final int ACCUMULATE_UNTIL_VERBALLY_NOTIFIED_OTHERWISE = 2;
    }

    // NoStrikes(428): INT
    public static final class NoStrikes {
        public static final int tag = 428;
    }

    // ListStatusType(429): INT
    public static final class ListStatusType {
        public static final int tag = 429;
    }

    // NetGrossInd(430): INT
    public static final class NetGrossInd {
        public static final int tag = 430;
        public static final int NET = 1;
        public static final int GROSS = 2;
    }

    // ListOrderStatus(431): INT
    public static final class ListOrderStatus {
        public static final int tag = 431;
    }

    // ExpireDate(432): LOCALMKTDATE
    public static final class ExpireDate {
        public static final int tag = 432;
    }

    // ListExecInstType(433): CHAR
    public static final class ListExecInstType {
        public static final int tag = 433;
        public static final char IMMEDIATE = '1';
        public static final char WAIT_FOR_EXECUTE_INSTRUCTION = '2';
    }

    // CxlRejResponseTo(434): CHAR
    public static final class CxlRejResponseTo {
        public static final int tag = 434;
        public static final char ORDER_CANCEL_REQUEST = '1';
        public static final char ORDER_CANCEL_REPLACE_REQUEST = '2';
    }

    // UnderlyingCouponRate(435): FLOAT
    public static final class UnderlyingCouponRate {
        public static final int tag = 435;
    }

    // UnderlyingContractMultiplier(436): FLOAT
    public static final class UnderlyingContractMultiplier {
        public static final int tag = 436;
    }

    // ContraTradeQty(437): QTY
    public static final class ContraTradeQty {
        public static final int tag = 437;
    }

    // ContraTradeTime(438): UTCTIMESTAMP
    public static final class ContraTradeTime {
        public static final int tag = 438;
    }

    // ClearingFirm(439): STRING
    public static final class ClearingFirm {
        public static final int tag = 439;
    }

    // ClearingAccount(440): STRING
    public static final class ClearingAccount {
        public static final int tag = 440;
    }

    // LiquidityNumSecurities(441): INT
    public static final class LiquidityNumSecurities {
        public static final int tag = 441;
    }

    // MultiLegReportingType(442): CHAR
    public static final class MultiLegReportingType {
        public static final int tag = 442;
        public static final char SINGLE_SECURITY = '1';
        public static final char INDIVIDUAL_LEG_OF_A_MULTI_LEG_SECURITY = '2';
        public static final char MULTI_LEG_SECURITY = '3';
    }

    // StrikeTime(443): UTCTIMESTAMP
    public static final class StrikeTime {
        public static final int tag = 443;
    }

    // ListStatusText(444): STRING
    public static final class ListStatusText {
        public static final int tag = 444;
    }

    // EncodedListStatusTextLen(445): LENGTH
    public static final class EncodedListStatusTextLen {
        public static final int tag = 445;
    }

    // EncodedListStatusText(446): DATA
    public static final class EncodedListStatusText {
        public static final int tag = 446;
    }
}
